### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-webextension#1]
_From @brantje on January 2, 2017 23:56_
Api docs [here](https://github.com/nextcloud/passman/blob/master/docs/api.md)
Browser extension:
- [x] Auto fill login form when credential matches (domain/path or page) ->   When more available show a dropdown
- [x] Ask to **save** password in Passman when a new password is detected (just like Chrome does)
  - [x] Auto generate a new password
- [x] Ask to **update** password in Passman when a new password is detected (just like Chrome does)
- [x] When extension icon is clicked the 'main' page is opened, showing the current amount of credentials found for current (domain/path or page) 
- [x] When a credential as a `otp` property, the extension should indicate that they can use the One time password generator from the extension. [OTP directive for angular js 1.*](https://github.com/nextcloud/passman/blob/master/js/app/directives/otp.js)
- [x] A settings page to lock certain settings like URL of NextCloud envoirment password settings etc. 
- [x] Strong encrypted communication in every way. 
- [x] WebExtensions compatible API!

Suggestions? Add them! 
Once i'll add them to the list i delete the comment to keep this issue clean.

Example settings page
![image](https://cloud.githubusercontent.com/assets/2758767/21597738/e1d0fb16-d14f-11e6-95c6-e7c49e7c0d1f.png)

_Copied from original issue: brantje/passman-chrome#1_

**Comment by brantje** [comment]
_From @enoch85 on January 7, 2017 13:45_

- [ ] Ask to **save** password in Passman when a new password is detected (just like Chrome does)
- [ ] Ask to **update** password in Passman when a new password is detected (just like Chrome does)

**Comment by brantje** [comment]
_From @evaryont on January 11, 2017 5:53_

Since Firefox has some compatibility with Webextensions (to a degree, they are adding extra APIs as they run into issues current extensions have when migrating) will Firefox be a target browser, too?

And since I expect others may ask, what about Opera (and even Vivaldi?) support?

**Comment by brantje** [comment]
_From @maestroi on January 11, 2017 7:1_

@evaryont eventualy firefox will be supported yes, but we think its best to support most used browser at the start.

About Opera depens highly on demand. we have no expierience with extension creation so we just start easy.

**Comment by brantje** [comment]
_From @tapir on January 12, 2017 8:42_

Please please please consider WebExtensions compatible API only. Your addon will work with chrome, firefox, edge and opera without any modifications.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions
Since this is a really simple plugin, it should be quite OK I think.

**Comment by brantje** [comment]
_From @maestroi on January 12, 2017 8:50_

@tapir thank you for the suggestion! we will look into that!

**Comment by brantje** [comment]
_From @tapir on January 12, 2017 8:52_

@maestroi there are some small incompatiblities listed here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities just FYI. The list is not long. With minimal care I believe your extension will work on all 4 big browsers. 💯 🥇

**Comment by brantje** [comment]
_From @maestroi on January 12, 2017 8:56_

@tapir thanks for the information!! i added them to the requirement list!

**Comment by nickvergessen** [comment]
*cough* Nextcloud not nextCloud *cough*

**Comment by brantje** [comment]
[API Docs](https://github.com/nextcloud/passman/blob/master/docs/api.md)

**Comment by kenthinson** [comment]
Should it have a local database that will sync with nextcloud? better performance on slow connections.

**Comment by maestroi** [comment]
@kenthinson only if its absolutly secure! syncing a DB will create a risk!

**Comment by kenthinson** [comment]
@maestroi Yeah that data will defiantly need to be encrypted in transport and well as on disk. But I think that if we want large companies to adopt pass man it will be needed to reduce the server load.

**Comment by animalillo** [comment]
i think we could start with an extension that just works, and then add local storage, planing it cautiously.

**Comment by tapir** [comment]
@animalillo 👍 
I think so too. Is there a roadmap or time plan for this extension?

**Comment by tapir** [comment]
I'm actually willing to help with this one. I've never done a WebExtension before but seems straight-forward.

**Comment by brantje** [comment]
@tapir would be very nice! We have a small passman dev group, poke me if you want to join (easier discussing things)

**Comment by brantje** [comment]
@tapir Atm there is no time plan. We're just in the planning phase. Currently writing a small js api for extensions. Still we need to decide if we want to use Angular / jQuery or good old plain JS.

**Comment by brantje** [comment]
@kenthinson Seems that our current extension is in no way compatible with Safari, or do they support webextensions? Sorry don't have any Apple products here ;)

**Comment by brantje** [comment]
All requirements met (+ few extra's). Extension will be published soon.

**Comment by animalillo** [comment]
think this is relevant here:
[Firefox](https://addons.mozilla.org/en-US/firefox/addon/passman/)
[chrome](https://chrome.google.com/webstore/detail/passman/hlpjhlifkgmoibhollggngbbhbejecph)

**Comment by jones4410** [comment]
firefox doesen't want to install the addon: addon seems to be damaged...?

**Comment by brantje** [comment]
It needs to be reviewed by mozilla before you can install it. At least i think that...

**Comment by animalillo** [comment]
Just read: "After Firefox 43 you can't install this extension until it's been reviewed".
![imagen](https://cloud.githubusercontent.com/assets/3353109/22794744/93839e92-eef4-11e6-9f14-a7b9a330e124.png)

**Comment by jones4410** [comment]
i know about this signature/review-thing of firefox-addons but I turned this of in config and it still results in the same error...?

**Comment by jones4410** [comment]
![grafik](https://cloud.githubusercontent.com/assets/22591354/22795062/955c9290-eef5-11e6-8c72-5415af972cb1.png)
sorry, couldn't change my browser language... but this is the error...

**Comment by jones4410** [comment]
now even the link to the passman-addon doesn't work :(

**Comment by brantje** [comment]
We have some scss file in the addon, and apparently mozilla doesn't want that.
I'll have to clean it up and send it again for review

**Comment by brantje** [comment]
Addon resubmitted to mozilla.

**Comment by jones4410** [comment]
ok thanks!

**Comment by brantje** [comment]
I think the flag you set is ignored since firefox 43.

**Comment by jones4410** [comment]
ohh, sorry, I wasn't informed about that... so I just can wait for Mozilla to do the signing?

**Comment by animalillo** [comment]
Either that or manually install it on every browser restart

**Comment by e-alfred** [comment]
Is it possible to have this extension in the Opera Web Store at https://addons.opera.com/? 

For now, installation is a bit problematic because Google does not like offshoots of Chrome/Chromium being able to install extension from the Chrome Web Store. After installing this addon  which allows installation from the Chrome Web Store within Opera (probably Vivaldi too) it is possible to install the Passman extension in Opera:

https://addons.opera.com/de/extensions/details/download-chrome-extension-9/?display=en
