### ISSUE TITLE
Feature Request: Support basic auth 

### ISSUE THREAD

**Issue by budachst** [nextcloud/passman-webextension#10]
### Steps to reproduce 
1. open a site, which caues Firefox to bring up a user/password dialog

### Expected behaviour
passman password icon should be visible

### Actual behaviour
no passman password icon visible

### Configuration
**Operating system**:   macOS 10.12.2

   
**Browser**:   Firefox 51.0.1 / Google Chrome 55.0.2883.75
   
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    2.1.0
       
       
**Nextcloud version**: 11.0.1

**Comment by brantje** [comment]
Err right, too little info, can you add what site you we're using?

**Comment by budachst** [comment]
Sure, here it comes…

<img width="1320" alt="bildschirmfoto 2017-02-19 um 17 31 16" src="https://cloud.githubusercontent.com/assets/10184884/23104194/57681f1e-f6c9-11e6-8bd5-0e6419b16e68.png">

**Comment by brantje** [comment]
Ah yeah. Http basic auth dialogs are not filled by the plugin. I haven't found any method to prefill those dialogs.

**Comment by budachst** [comment]
I am wondering how Laspass does it. At least there seems to be a way. Mozilla wouldn't pass an extension/plugin, that does something undocumented, would they?

**Comment by brantje** [comment]
Seems that this plugin also fill in HTTP basic auth dialogs: https://github.com/pfn/passifox

**Comment by adocampo** [comment]
I don't want to reopen this, but I see it should be closed by now?
I think transmission web interface uses basic auth and the extension doesn't recognize the dialog. So I guess this issue still exists.

**Comment by brantje** [comment]
Can you post a screenshot of that dialog?

**Comment by adocampo** [comment]
Sure.
This one shows the dialog: http://imgur.com/ePKwCtQ
If you fail, an apache error appears, that's why I think is apache authentication: http://imgur.com/7MIzYGG
This other screenshot shows the same dialog with the keefox add-on enabled, to show you one add-on which can access to this dialog. http://imgur.com/mN56uUQ

**Comment by budachst** [comment]
Yeah… I just checked out the latest extension and loaded it temporarily in FF 51 and the issue still persists. The dialog just won't fill with the credentials available.

**Comment by rugk** [comment]
Actually this should be possible with WebExtensions using `webRequest.onAuthRequired`.

**Comment by brantje** [comment]
Actually this is already in the extension. See: https://github.com/nextcloud/passman-webextension/blob/master/js/background/service/httpAuth.js
