### ISSUE TITLE
No credential shown when clicking ion icon in textbox

### ISSUE THREAD

**Issue by Draky50110** [nextcloud/passman-webextension#103]
Hello.

Firefox addon 1.4.1 : when I click on the blue icon in a password area, nothing shows !

![passextfirefox](https://user-images.githubusercontent.com/1558487/27726353-6d6ebe54-5d7a-11e7-845d-03e5e0fbd647.png)

**Comment by brantje** [comment]
Ah yea, that's because the tabs are remembered. Just click on the list icon and you will see your credentials.

**Comment by Draky50110** [comment]
Completely closed Firefox, reopened it : still same problem : icon in toolbar gives credentials, not in textarea :(

**Comment by Draky50110** [comment]
New clue : clicking on the search icon in this tiny bar then back to list, it displays credentials.

So problem occurs only on "first click and display".

**Comment by brantje** [comment]
More like this
![afbeelding](https://user-images.githubusercontent.com/2758767/27726702-c129e9dc-5d7b-11e7-8b78-ebb8d26d7a91.png)
