### ISSUE TITLE
Cache passwords locally

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#104]
### Steps to reproduce
1. Log in into PassMan with a vault with > 100 passwords or so.

### Expected behaviour
You should instantly have your passwords available and so on…

### Actual behaviour
Passman seems to have to fetch the passwords first from the server.

This is bad in two cases:
1. As explained, with many passwords, it is slow and one needs to wait some seconds, which causes a bad UX.
2. When you are having a slow network connection, or maybe no network connection at all (travelling with your laptop…), you also want to have your passwords available. It would be horrible to see, you cannot access some LAN services (router, etc.)…

That's why you should cache the credentials offline, in an encrypted format, of course.

### Configuration
**Operating system**:   Linux
 
**Browser**: Firefox 54.0

**Extension version**:  1.4.1
       
**Nextcloud version**: 12

**Comment by brantje** [comment]
I won't cache passwords locally, this because it will cause a security thread.
Also offline support is not planned for the extension, you need internet to access the websites anyway.
I use passman and the extension with over 300 passwords, just be patient.

**Comment by animalillo** [comment]
We are planning a revamp of server side encryption which should speed up your vault load times! ;)

**Comment by brantje** [comment]
Also, down voting won't reopen the issue, if you want this you can implement it and send a PR. 
We will take a look and if it works and it's secure we will merge it.

**Comment by rugk** [comment]
He, I think "offline support is not planned for the extension"? This would mean you do not accept PRs on this. If you accept PRs I would suggest to leave this issue open and tag it with "help wanted" (or a new tag, if you want).

**Comment by maestroi** [comment]
Caching, is a bad idea, this wil create a unnecessary risk(if its local it can be hacked/bruteforced), but i understand your frustration

In order for a solution
1. wat do you consider  a "slow" connection?
2. how many seconds do you need to wait?

**Comment by rugk** [comment]
> wat do you consider a "slow" connection?

GSM, EDGE? When using tethering with your phone or a laptop with SIM slot.

> how many seconds do you need to wait?

2-3. The first time this surprised me heavily, as I thought something did not work. (Usually you unlock your vault and want to login right away, maybe only refresh the current site…)

**Comment by animalillo** [comment]
the actual size is not a problem, most of the time, the issue with loading times is with the server side encryption, that is makin a heavy encryption task on the server side, so we plan to revamp that part a bit for it to load way faster and the exact same safe!

**Comment by animalillo** [comment]
Also adding client side cache won't fix any issue with loading times cause you still need to refresh the full vault from time to time to know if something changed.
It would only increase extension complexity and also, most desktop users don't use gsm or edge connections.

If somebody made a pull request it would be reviewed and might be accepted, but keeping an issue that we don't ever plan to add support with makes absolutely no sense.

**Comment by rugk** [comment]
> Also adding client side cache won't fix any issue with loading times cause you still need to refresh the full vault from time to time to know if something changed.

Right, but users would not notice it is loading in most cases. Likely the first site they login after logging in does not have a new password or so, and they can just login. Also the sync could be faster as it only needs to sync the changed passwords/delta…

> but keeping an issue that we don't ever plan to add support with makes absolutely no sense.

It is a sign for potential contributors that this issue is "open to grab".

**Comment by maestroi** [comment]
@rugk if there are much more people that want this feature, we can take a look but for now we have other priorities. Thanks for the reporting this issue.

**Comment by animalillo** [comment]
rugk, we don't have any way to detect changed passwords, that's why i don't see any benefits from caching

**Comment by rugk** [comment]
Okay, another idea would be to at least display a loading icon somewhere (in the icon instead of the red lock?) to show that the vault is being encrypted…

**Comment by brantje** [comment]
We can only show text in that place, maybe a red passman icon does the job to show that the vault is being loaded?

**Comment by rugk** [comment]
The red Passman icon already shows that the vault is locked. Maybe a yellow one making it a traffic light? :vertical_traffic_light:

**Comment by brantje** [comment]
How about the `↻` icon?

**Comment by rugk** [comment]
Yeah, also possible.

**Comment by Arc676** [comment]
Side note: the reason I came looking for an offline cache isn't because of loading speeds, but because I self-host my Nextcloud and it's not accessible over the web (I don't have control over my home network). Since the extension doesn't keep a copy of the database, it does nothing at all when I'm not at home. And at home, instead of my laptop, I just use the PC that's running the Nextcloud instance, which makes this problem moot.

I guess the workaround is to just use a normal standalone password manager instead.
