### ISSUE TITLE
Remove entries from the web extension

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#105]
It would be great to have the chance to delete a wrong/duplicate entry directly from the web extension. I have more than a thousand entries and it's a bit slow to open the nextcloud passman application to edit entries. But sometimes I found a wrong or duplicate entry when I'm browsing, so deleting entries in two click would be awesome!

**Comment by brantje** [comment]
@adocampo with 1000+ items, how long does it take to open the vault? For the new passman version (with vault sharing), we have planned to optimize the server side encryption

**Comment by adocampo** [comment]
It takes 13s the first time (when I'm on the Files app and click on Passman), when I enter into a edit view or settings, and turn back the password list inside Passman app, it takes 10 seconds to load the password list.

**Comment by brantje** [comment]
The time required to load the list will decrease soon. Also i'm looking into way's to prevent vault reloading after an edit.

**Comment by adocampo** [comment]
It will be great, anyway, what do you think about the proposal? I think it can be helpful...
