### ISSUE TITLE
Can't install extension on Chrome via sources

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#106]
### Steps to reproduce
1. Clone the git repository
2. Go to chrome://extensions/
3. Click on Load Unpacked Sources

### Expected behaviour
The extension loads normally

### Actual behaviour
Chrome can't load the extension and raises an error: Variable $CREDENTIAL_AMOUNT$ used but not defined.

### Configuration
**Operating system**:   
Linux, Ubuntu 16.04 LTS
   
**Browser**:   
Chrome Version 59.0.3071.115 
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    

**Extension version**:    
Last commit on master      
       
**Nextcloud version**:
   
#### Browser log
Échec du chargement de l'extension depuis : ~/workspace/web/passman-webextension
Variable $CREDENTIAL_AMOUNT$ used but not defined.

**Comment by brantje** [comment]
The extension is in the chrome store, see readme for location.
As for the translations, this is a transifex bug, you need to run `fixLocale.js` with NodeJS.
The bug has been reported to transifex.

**Comment by dardelet** [comment]
I have installed via the chrome store, but I want to contribute hence my trying to install via sources.

Running `node fixLocale.js` fixed it, thank you !

**Comment by brantje** [comment]
Oh nice! We're looking forward to your contribution!
