### ISSUE TITLE
@rakekniven

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-webextension#107]
@rakekniven Please do not push to master

**Comment by brantje** [comment]
Also your commit is not signed. Please only push signed commits to any passman related repo.

**Comment by rakekniven** [comment]
Hello @brantje 
Damn, made two mistakes in one step.
Pushing to master was not intended, sorry. 
Just curious, could you prevent to commit to master by settings e.g. like nextcloud/server?

Regarding signing: I forgot to add signing info like I did now here: https://github.com/nextcloud/passman-webextension/commit/9f79b9b66b4e5e3d33f0e37b5a8d006d5ab08f31

As a non git command line user (using GitHub only via browser) I would like to know if this is valid?

**Comment by animalillo** [comment]
Commits should be signed using GPG, so we get this neat badges
![imagen](https://user-images.githubusercontent.com/3353109/27965099-d8fd850e-633a-11e7-8a9d-b63be4ee3f38.png)

**Comment by animalillo** [comment]
(note is not only because of the badges, but for the added security)

**Comment by rakekniven** [comment]
Understood, do you make a difference if somebody is changing code which is influencing function and people like me improving documentation and translation stuff.

Using git command line with gpg would be more effort for me.

**Comment by animalillo** [comment]
make a pull request, we might merge it and sign it in the process

**Comment by rakekniven** [comment]
Hello @animalillo 
have two PR open:

* https://github.com/nextcloud/passman/pull/283
* https://github.com/nextcloud/passman/pull/330

Thanks for taking care about it.

Will try to use git cli in the future.

Have a good weekend.

**Comment by brantje** [comment]
Thanks, we will look at the PR's when we get some time =).
