### ISSUE TITLE
No explicit error if url is invalid in setup page

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#108]
### Steps to reproduce
1. Install passman extension on Chrome
2. Enter invalid **server url** and any username / password 
3. Hit Next

### Expected behaviour
There should be an "Error connecting to server" error like when the url is correct but username/password 
### Actual behaviour
Nothing happens and the spinner on the next button spins forever

### Configuration
Linux, Ubuntu 16.04

**Browser**:   
Chrome Version 59.0.3071.115
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    

**Extension version**:    
commit 08883d57295abb1c981b4a863b10b41d8525fda9
       
**Nextcloud version**:
 11

#### Attempt at fixing
I tried to figure out a solution and saw that the error was [here](https://github.com/nextcloud/passman-webextension/blob/master/js/lib/api.js#L224).
At this line the following error is raised: 
```
api.js:226 Uncaught (in promise) TypeError: Cannot read property 'create' of undefined
    at api.js:224
    at <anonymous>
```
I'm guessing this is related to the way Chrome handles promises and that I need to to something like [this](https://github.com/nextcloud/passman-webextension/blob/master/js/lib/API/notifications.js#L23-L32) but I'm still figuring out the codebase and I don't understand the difference between API and API.api

**Comment by brantje** [comment]
Fixed with PR #111
