### ISSUE TITLE
Open site directly from passman extension

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#109]
I think this was somehow discussed before, but I would like to request a cool feature for passman widget.

What do you think about clicking on the passman widget --> search field --> show coincidences --> click on one result --> open a new tab passing the credentials for that site.

Now we can search, but the items on the results list are not clickable, just editable. 

I would make search more useful and prominent (i.e.: instead making search a submenu inside the menu, I would make a field (with the magnifying glass icon like in nextcloud) on top of the main UI, besides the refresh or so.) 

I think passman is VERY useful, but a bit uncomfortable (i.e.: open a new tab --> going to the wanted site --> click on login inside the site --> pointing and clicking on passman icon besides the login field --> selecting the credentials --> clicking on validate button) to use. With this proposal we could enter a site with two clicks of a mouse.

**Comment by brantje** [comment]
Yea, some kind of auto login is quite complex. For this feature to work it's needed to set the url to the login page for example, which won't be user friendly imo.

The open site action is possible, i can open a new tab with the site url.

**Comment by adocampo** [comment]
Opening the site directly from the search results would indeed accelerate the process :) yet autologin would be a killing feature!
