### ISSUE TITLE
Manually added URLs not selectable

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#110]
### Steps to reproduce
1. Save a password for URL=domain.example in the add-on (for a single-password/password-only field)

### Expected behaviour
Next time allow password to be selected from list in field.

### Actual behaviour
**Edit:** The password does not show up in the password-picker.

When you manually search for the password and select it, you get this message:
> Geänderte URL gefunden für: null at […]/threema/#/welcome

This claims the URL field is `null` while actually it already contained the URL mentioned. And even when clicking on "update" in this message the next time the message appears again.

### Configuration
**Operating system**: Linux

   
**Browser**: Firefox 54.0

**Extension version**: Passmann extension 1.4.2 
       
       
**Nextcloud version**: 12

**Comment by rugk** [comment]
Screenshot of password entry:
![exampel](https://user-images.githubusercontent.com/11966684/28013645-03ed5510-656a-11e7-8590-967a3f224da3.png)

**Comment by brantje** [comment]
.... dude you have another issue open about this #95

**Comment by brantje** [comment]
Also give the extension some time to refresh.

**Comment by rugk** [comment]
I have not. You already implemented filling passwords in https://github.com/nextcloud/passman-webextension/commit/2fdaa6491b399dece809f507da06065390eed905 and theoretically this should work. This issue is not really about the password-one-liner, but rather about the fact that the **manually added** passwords cannot be selected.

See title: **manually added**!

And reopen, please.

**Comment by rugk** [comment]
Also I have no idea what you mean with:
> Also give the extension some time to refresh.

Time does not mater here. I can reliably reproduce this issue (even when the password has been added days ago…).

**Comment by brantje** [comment]
you mean the account doesn't show up in the password picker?

**Comment by rugk** [comment]
Right.

**Comment by rugk** [comment]
So can you finally reopen this issue, please?

**Comment by brantje** [comment]
@rugk, do you know we do this project for free and when we have some time off, right?

We can't keep an eye at github at all the time, we can't fix all the tiny itzy little bit issues that pop up and don't break shit apart because we have to focus on the important features and bugs. We try our best to keep this up, free and working smoothly.

**Comment by rugk** [comment]
Are you kidding? I only want that you **reopen** this issue, as you saw it is valid and is not fixed yet. If it will not be fixed that fast it does not matter, but open this issue finally. You closed it more or less as a duplicate, which was wrong and thus this issue needs to be reopened.
And you have enough resources to press a button on GitHub here. (It's way easier than to write such confusing responses…)

**Comment by rugk** [comment]
Should I open a new issue for this or would you finally mind to open this issue?
And if you have no time for using an issue tracker, then you should not use an issue tracker…

**Comment by rugk** [comment]
Thanks. :tada: :+1:

**Comment by rugk** [comment]
I can confirm that this issue is fixed.
