### ISSUE TITLE
Focus should be in input fields

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#114]
### Steps to reproduce
1. Click on the main icon (to unlock the vault)
2. Type your password instantly.

The same thing happens when you click on the box in a website and have it set to open the search input field or you click on the search icon and afterwards, instantly typing in the thing to search does not work.

### Expected behaviour
It should be typed into the input field for the master password.

### Actual behaviour
Maybe the password gets typed into the currently opened website? 😱

### Solution

Always auto-focus an input field, when it is shown.

### Configuration
**Operating system**: Linux

**Browser**: Firefox 54.0 & Chrome 59

**Extension version**: 1.4.2 
       
**Nextcloud version**: 12

**Comment by brantje** [comment]
Seems this is a (bug)[https://bugs.chromium.org/p/chromium/issues/detail?id=121006] in chrome.

**Comment by rugk** [comment]
OH, well, ups, I forgot to browser name in my issue. It also affects Firefox. Or better: I only tested this in Firefox.

**Comment by brantje** [comment]
I've edited the issue to indicate it affects both browsers.

**Comment by rugk** [comment]
Okay, currently I tried to reproduce it another time and it worked. However, after closing the popup and clicking on this GitHub input field, opening the popup again it does not work.

**Comment by brantje** [comment]
Yea input fields in browser popups are kinda 'special'. Seems the `autofocus` attribute doesn't always work.

**Comment by rugk** [comment]
I've submitted a bug for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1381254

**Comment by brantje** [comment]
For that issue they can also try the following HTML:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Example</title>
        <meta charset="UTF-8">
    </head>
    
    <body>
        <div id="layout">
            <form action="#">
                <input type="text" name="test" size="30" autofocus="autofocus">
            </form>
        </div>
    </body>
</html>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Example</title>
        <meta charset="UTF-8">
    </head>
    
    <body>
        <div id="layout">
            <form action="#">
                <input type="text" name="test" size="30" autofocus="autofocus">
            </form>
        </div>
    </body>
</html>
```
Easier to test than setting up the whole extension.

**Comment by brantje** [comment]
Closing, feel free to open an new one after they fixed the problem.
