### ISSUE TITLE
Login forms created by JavaScript are not detected

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#118]
### Steps to reproduce
This can best be reproduced on bountysource:
1. Go to the homepage https://www.bountysource.com/.
2. On the top-right click on Sign in -> e-mail address
– The login field stays empty. –
4. Now reload.

### Expected behaviour
Already in step 2 the credentials should be filled-in.

### Actual behaviour
Only after reloading the Passman icons appear in the input fields and the credentials are auto-filled.
This means input fields are only detected at page load, not when added by JavaScript afterwards.

### Configuration
**Operating system**: Linux

**Browser**: Firefox 54.0

**Extension version**: 1.4.2 
       
**Nextcloud version**: 12

**Comment by rugk** [comment]
Hmm, "feature request" or "bug"? Depends on the view point, I think. :smiley:

**Comment by brantje** [comment]
Feature, as it's currently not build into the extension.
Problem is that checking the DOM periodically would put extra load on the client.
At the moment the extension runs even nice on a rpi, and i want to keep it that way.

**Comment by rugk** [comment]
Sure, but even Firefox internal password manager supports this feature, so it's likely possible to do in a reasonable way…

**Comment by brantje** [comment]
Well the [code](https://github.com/nextcloud/passman-webextension/blob/master/js/background/inject/inject.js#L273) is there :p. 
Just untested, maybe @dardelet want to give this a shot?

**Comment by dardelet** [comment]
@brantje absolutely !

**Comment by brantje** [comment]
Fixed in master. Github didn't detect the merge

**Comment by Jurik-Phys** [comment]
I have this bug on linux.org.ru. On the top-right click on "Вход" (Russian Sign in) login fields don't detected by extension (no icon, no inserted text). But after try login with zero fields new login form detected by passman.
