### ISSUE TITLE
Bar covered on WordPress backend

### ISSUE THREAD

**Issue by Mte90** [nextcloud/passman-webextension#120]
### Steps to reproduce
1. Login on the backend of a wordpress website
2. you don't see the bar
3. 

### Expected behaviour
See the bar

### Actual behaviour
![screenshot_20170717_165924](https://user-images.githubusercontent.com/403283/28274948-ba2996f6-6b12-11e7-9b9a-793d31de1059.png)

### Configuration
**Operating system**: Linux

**Browser**: Firefox

**Extension version**: 2.0.0

To fix it I tried in the inspector and I put the bar in the dom before the closing </body> tag and fixed the problem.
In any case to detect if the page is on WordPress backend the body tag has the class `wp-admin` so in case you can add the support for that if the body has this class :-)

**Comment by brantje** [comment]
That would fix the issue only on WordPress sites. Can you try adding a z index to the element? I don't have access to a WordPress site to debug this.

**Comment by brantje** [comment]
Found a demo instance, and fixed it with adding a z-index. This way it will be solved on most, if not all sites =).
![image](https://user-images.githubusercontent.com/2758767/28278890-f5c1c998-6b1e-11e7-81a3-ef2ed31ac567.png)
