### ISSUE TITLE
Password picker is not removed when changing pages is done with javascript

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#123]
### Steps to reproduce
1. Go to https://www.bountysource.com/signin 
2. Click on the icon to make the password picker appear
3. Click on the bounty source logo to go back to the home

### Expected behaviour
Password picker should be removed

### Actual behaviour
Password picker is not removed
![screen shot 2017-07-17 at 23 26 18](https://user-images.githubusercontent.com/7913565/28290748-ec2214c8-6b47-11e7-9071-56618ddfbccb.png)

**Comment by brantje** [comment]
Note: Checkout the `fix-issue-118` branch .
