### ISSUE TITLE
Phrasing in the settings

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#127]
### Steps to reproduce
1. Go to settings

### Actual behaviour
There is an on/off button for these 2 settings:
Disable form autofill
Disable password picker
which is confusing because when the button is on, the feature is deactivated.

### Expected behaviour
Should be
Enable form autofill
Enable password picker

**Comment by brantje** [comment]
I think best way is to rename the settings property, this way we can migrate from the old the the new (inversed)  property easily.
