### ISSUE TITLE
Save button in password picker not working

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#128]
### Steps to reproduce
1. Go to https://www.kraken.com/login 
2. Go on the first tab of the password picker
3. Enter credentials manually and hit Save

### Expected behaviour
Credentials should be saved

### Actual behaviour
There is an error that prevents saving, and no visual feedback. 

### Fix
Need to add a "select account" entry in the form

**Comment by brantje** [comment]
![image](https://user-images.githubusercontent.com/2758767/28436451-5278e6a6-6d97-11e7-960c-b7c6c7d978ee.png)
