### ISSUE TITLE
provide version number in extension

### ISSUE THREAD

**Issue by budachst** [nextcloud/passman-webextension#14]
It would be good, if the web-extension could show it's version number somewhere.

**Comment by brantje** [comment]
Of the extension it self?

**Comment by brantje** [comment]
For chrome it can be found [here](chrome://extensions/)   
![image](https://cloud.githubusercontent.com/assets/2758767/23266934/8434bfde-f9e9-11e6-9060-f13e97af7878.png)

For firefox it can be found [here](about:addons)
![image](https://cloud.githubusercontent.com/assets/2758767/23266985/a87676e4-f9e9-11e6-8eed-8cff0924201f.png)
And click on `More`

**Comment by budachst** [comment]
Okay, that's true but usually, people would rather click on the extension icon than to go to the add-ons menu and clicking more on the passman web extension. In the end the extension is, where people deal with it and it seems "natural" to me.

**Comment by brantje** [comment]
Point taken, i guess somewhere in the settings is a good place for it

**Comment by budachst** [comment]
Great! Thanks!

**Comment by brantje** [comment]
Example
![image](https://cloud.githubusercontent.com/assets/2758767/23267579/73eaf218-f9eb-11e6-8dc9-a80ac35e8502.png)

**Comment by budachst** [comment]
Perfect!
