### ISSUE TITLE
After selecting account in the picker, the picker is not closed

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-webextension#140]
### Steps to reproduce
1.  Open password picker
2.  Pick account
3.  Profit

### Expected behaviour
Password picker should close

### Actual behaviour
The password picker stay's open

**Comment by dardelet** [comment]
Could it be related to this ? https://github.com/nextcloud/passman-webextension/pull/136

**Comment by brantje** [comment]
Don't think so... Need to check if the picker also closes after creating a credential.

**Comment by dardelet** [comment]
I meant the typo in "enablePasswordPickerr".
