### ISSUE TITLE
Passman startup failure on Chrome

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/passman-webextension#141]
![passman_bugged](https://user-images.githubusercontent.com/6317548/28576667-c102174e-7154-11e7-8f3a-111bcb366e85.png)
 
### Steps to reproduce
Not sure if this will be reproducable for others. However for me the issue was caused after:
1.  Install and setup the passman chrome extension on device 1 (in my case a windows machine - don't think it matters).
2. Open chrome on device 2 (a linux machine in my case) and wait until  the extensions are synchronized.
3. try to open the Passman extension by clicking on the icon in the right upper corner.

### Expected behaviour
Passman shows the setup dialog (requesting next-/owncloud domain and credentials) - that or it is already configured and shows the list of credentials for the current site.

### Actual behaviour
The dialog is bugged (see attached image) and there is a log message in the JS console saying `[Passman extension] Stopping, vault key not set -- inject.js:328`

### Things I tried so far
* Try to install the passman extension in a fresh chrome profile (without reinstalling chrome and without synchronizing anything) - to the same result.
* Try to delete any extension cache and configuration of Passman I could find in the chrome config directory - to no avail

### Things I didn't try
* Reinstall chrome on the linux machine

### Configuration of machine 1
**Operating system**: Windows 7 64 bit

**Browser**: Google Chrome (latest version I think, 50.*; can't verify until in two weeks)

**Extensions that might cause interference**: None - tried to disable any other extension.

**Passman version**: 2.1.2

**Extension version**: 2.0.0 as well as 2.0.1

**Nextcloud version**: 12.0.0
   
### Configuration of machine 2
**Operating system**: Debian 64 bit

**Browser**: Google Chrome (latest version I think, 50.*; can't verify until in two weeks)

**Extensions that might cause interference**: None - tried to disable any other extension.

**Passman version**: 2.1.2

**Extension version**: 2.0.0 as well as 2.0.1

**Nextcloud version**: 12.0.0
   

### JS log
`[Passman extension] Stopping, vault key not set -- inject.js:328`

**Comment by brantje** [comment]
Thanks for reporting this issue.
As you say, this one will be hard to reproduce. I'm using the extension with some different configurations without problems:
- Windows 10 -> Both firefox and Chrome at work
- Windows 10 + Linux -> Chrome / Chromium / Firefox at home
- MacOS -> Firefox and chrome on the test mac

Can you enable developer mode for extensions? You can do that [here](chrome://extensions/#dev-toggle).
After that, open the passman extension, right click in the popup and click on `Inspect Element`.
A new window will open, click on it. After that press `F5` to reload the popup. 
Then click on a tab called `Console`. Make a screenshot of it and paste it here.
Hopefully we see some errors.

**Comment by theCalcaholic** [comment]
I tested again to install Passman after having removed all Profile directories. The result is the same - which should mean that the issue is actually not related to Chrome's profile-synchronisation.
Furthermore that implies that the Windows system is not relevant to the issue.

The logs yielded interesting results after having activated Dev mode and reloading (as you suggested):

    Error: Invalid arguments to connect.
        at Object.updateArgumentsPreValidate (extensions::runtime:142:13)
        at Object.<anonymous> (extensions::binding:372:30)
        at Object.API.runtime.connect (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/API/runtime.js:77:32)
        at new <anonymous> (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/ui/popup/controllers/main.js:38:36)
        at Object.invoke (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:4841:19)
        at $controllerInit (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:10694:34)
        at nodeLinkFn (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:9571:35)
        at compositeLinkFn (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:8880:13)
        at compositeLinkFn (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:8883:13)
        at publicLinkFn (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:8745:30)

**Comment by brantje** [comment]
I use Chrome 59. My best guess is that the browser needs to be updated.

**Comment by theCalcaholic** [comment]
That was ist. -_-
I wasn't aware that there is no automated update mechanism for chrome on Linux. Sorry, that was a waste of time. >.<
