### ISSUE TITLE
Feature: Clearing the extension data

### ISSUE THREAD

**Issue by dasisdormax** [nextcloud/passman-webextension#144]
### Actual behaviour
Currently, there is no option to "start over" with configuring the extension, for example when you mis-typed the extension master password on creation. As Firefox has no option to delete an extension's data (even by deleting and re-installing the extension), you would have to dig in your firefox profile and search for the correct file to delete.

### Expected behaviour
On the extension lock screen, show a button like "Forgot Password? Reset this extension".

### Configuration
**Operating system**: several OSes (Windows 10, Arch Linux)

**Browser**: Firefox 54.0.1

**Extensions that might cause interference**: ???

**Passman version**: 2.1.2

**Extension version**: 2.0.0

**Nextcloud version**: 12.0.0

**Comment by brantje** [comment]
What if someone uses your PC and resets the extension? In the nextcloud app this is prevented by logging in as your user.

**Comment by dasisdormax** [comment]
Well, thanks!

I don't think we can protect the user from someone else resetting the extension effectively. That someone else could just go around that protection by deleting that storage json through the filesystem.

**Comment by animalillo** [comment]
>format c:
>sudo rm -rf --no-preserve-root /
everything is gone now

(_*ps, don't run that commands if you don't want to cry*_)
