### ISSUE TITLE
Reconize only specific fields

### ISSUE THREAD

**Issue by Mte90** [nextcloud/passman-webextension#146]
### Steps to reproduce
1. It is not possible to reproduce because the site is closed
2. 
3. 

### Expected behaviour
Fields ignored, a flag to ignore this fields or page to show that data but leave for the rest of the website.
### Actual behaviour
The site has pages for login but because is a support system they have fields for asking to the user the login data in that way they can check what they need but the extension fills that fields with my login data of the support website.

The screen contain the inspector with the element dom stuff to replicate.

![screenshot_20170731_131851](https://user-images.githubusercontent.com/403283/28775654-6fb4edbe-75f3-11e7-9d38-c0a55c4589c7.png)

**Comment by brantje** [comment]
Did you know you can ignore the domain? We could extend it to ignore the domain + path

**Comment by Mte90** [comment]
Yeah sure but I want that my login data are accessible from the website except that page

**Comment by brantje** [comment]
@Mte90 how does this look
![image](https://user-images.githubusercontent.com/2758767/28879555-bffc27a0-77a2-11e7-8edd-fcf1bafc77f4.png)

**Comment by Mte90** [comment]
Seems amazing!

**Comment by brantje** [comment]
@Mte90 For now you can fill in the url in settings
