### ISSUE TITLE
Password generator settings ignored 

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#150]
### Steps to reproduce
[passwordsettings.zip](https://github.com/nextcloud/passman-webextension/files/1202246/passwordsettings.zip)

### Expected behaviour
Generate password.

### Actual behaviour
Ignores all settings.

### Configuration
**Operating system**: Linux

**Browser**: FF 54.0.1

**Passman version**: 2.1.4

**Extension version**: 2.0.0

**Nextcloud version**: 12
   
#### Browser log
<details>
<summary>Browser log</summary>
```

TypeError: pw_settings_form.serializeObject is not a function[Weitere Informationen] password_picker.js:164:28
	setupPasswordGenerator/</< moz-extension://cb58c161-b5db-4790-8eb5-d598a7dc5d2a/js/ui/password_picker/password_picker.js:164:28
	dispatch moz-extension://cb58c161-b5db-4790-8eb5-d598a7dc5d2a/js/vendor/jquery/jquery.js:5200:16
	add/elemData.handle moz-extension://cb58c161-b5db-4790-8eb5-d598a7dc5d2a/js/vendor/jquery/jquery.js:5009:6
```

</details>

**Comment by brantje** [comment]
Perfect timing, just started working on #146, after that will look into this one.
