### ISSUE TITLE
Passman should override desktop themes

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#155]
### Steps to reproduce
1.  On Plasma Desktop (aka KDE), go to settings --> application style --> GNOME/GTK --> GTK Themes and select Breeze dark
2. Once applied the theme, open firefox and now menus are black
3. Textboxes on passman web extension are also black, which is ok, but text is dark gray, very difficult to read.

### Expected behaviour
Textboxes background color should be white

### Actual behaviour
Textboxes background color is black

### Configuration
**Operating system**:  Arch Linux 64 bits

**Browser**: Firefox

**Extensions that might cause interference**: None

**Passman version**:  2.1.4

**Extension version**: 2.0.0

**Nextcloud version**: 12.0.0

I don't know in other OSes and desktops, but in linux with plasma with a dark desktop theme, passman text fields are black and input characters are in dark grey, so they are pretty difficult to see.
![Like This](http://i.imgur.com/CJnyNJN.png) ![Like This](http://i.imgur.com/Zj5yKwj.png)

Perhaps is easy to apply a CSS on the textfields to show them always as expected.

**Comment by brantje** [comment]
What os? Please use the issue template

**Comment by adocampo** [comment]
Modified!
