### ISSUE TITLE
[Feature Request] Add Password generator

### ISSUE THREAD

**Issue by FrederikLauber** [nextcloud/passman-webextension#158]
Hello,

it would be very nice if we could get an embedded password generator so I can generate a secure password (for an example, just have a look at LastPass) within a few clicks.
Options would be length of password and character set (maybe A-Z, a-z, 0-9, special characters)

Thanks in advance

**Comment by brantje** [comment]
This is already implemented.

Right mouse: 
![image](https://user-images.githubusercontent.com/2758767/29125134-39ec5bb6-7d1b-11e7-8a37-9d9880b55575.png)

Or at the password picker:
![image](https://user-images.githubusercontent.com/2758767/29125156-4a14cc62-7d1b-11e7-89c4-eeb8a084ecb3.png)

**Comment by FrederikLauber** [comment]
Ah okay, still, it would be very nice if we had this as a more prominent feature.
Maybe add it to the bar here? 
![2](https://user-images.githubusercontent.com/17728264/29126830-b4ebe1ac-7d1f-11e7-9fac-72b3de198808.png)


Also, using the right click, generate password will not give you the option to change the generated password (like changing the character set) so it would be very nice if I could pop up the posted password generator from there somehow. 

Maybe some background. Trying to switch from LastPass to passman atm and was looking for the password generator for over 30 minutes. Btw, why does this context menu somehow show up and sometimes not? Tried first with the google search and it does not show up there...

**Comment by FrederikLauber** [comment]
![3](https://user-images.githubusercontent.com/17728264/29128804-282b22a4-7d25-11e7-94e9-0e772302ef2a.png)

Btw, it also does not show up for many password fields...
Is there something I can do to get this working?

**Comment by brantje** [comment]
All settings are global, so if you change it in the password picker it will also reflect the settings under the right click menu.   
The context menu only shows if there are logins, this was a bug and is fixed in master.

Field matching is done by looking for a password field and a text field on the page.
A passman icon will appear in the input fields if passman recognized the login form. 

If you would like to know which files are used

**Comment by FrederikLauber** [comment]
Hi,
maybe I should have been more clear.
I meant that I need to change the char set not globally but locally for one given password.
My normal password policy is: 100 Chars, all available chars.
Unfortunately, many websites limit this in different ways. So some only accept 16 letters but from the hole charset, others allow 100 letters but do not allow special characters.
Some of them are even incompatible with each other (for example no special chars vs at least one).

So having the ability to change this on a per by per basis with the global setting as the default is in my eyes imperative.

**Comment by paulcalabro** [comment]
I had to hunt for the settings in the second screenshot. I knew I had see it before, but it wasn't available by clicking the extension directly and viewing options there. It would be nice if it was exposed here as well for times where I'm not creating a new password, but I want to update a new password and increase the password complexity.

> This is already implemented.
> 
> Right mouse: ![image](https://user-images.githubusercontent.com/2758767/29125134-39ec5bb6-7d1b-11e7-8a37-9d9880b55575.png)
> 
> Or at the password picker: ![image](https://user-images.githubusercontent.com/2758767/29125156-4a14cc62-7d1b-11e7-89c4-eeb8a084ecb3.png)
