### ISSUE TITLE
Invalid server settings!

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#16]
### Steps to reproduce
1. Install chromium addon via chrome web store
2. Click on the addon icon to configure it
3. Fill the fields, server URL, user and password (App password, I have enabled OTP)
4. Click next, then the Invalid server settings banner appears.

### Expected behaviour
To login into my nextcloud server.

### Actual behaviour
I can't advance and finish the addon configuration.

### Configuration
**Operating system**:   
NC Server: Arch linux docker container.
Client: Arch linux.
   
**Browser**:   
  Chromium 56.0.2924.87 (64-bit)
   
**Extensions that might cause interference**:   
None, I tried disabling all extensions but this one.   
   
**Passman version**:    
2.1.1
       
       
**Nextcloud version**:
   11.0.1
#### Browser log
I don't know how to attach any log from chromium, I cannot see anithing on the web developer console related to the extension.

**Comment by brantje** [comment]
Do you use http or https?

**Comment by adocampo** [comment]
https

**Comment by brantje** [comment]
If you open the popup you can right click on it and inspect an element. 
Keep this window open and go through the setup, after you click `Finish` you should see something in the console.

**Comment by adocampo** [comment]
Could be a net::ERR_INSECURE_RESPONSE?
I'm using https but I haven't configured yet letsencrypt and it's a self-signed certificate at the moment.

`GET https://malevolent.bofhers.com/nextcloud/index.php/apps/passman/api/v2/vaults net::ERR_INSECURE_RESPONSE
api_request @ api.js:140
getVaults @ api.js:18
server @ setup.js:64
(anonymous) @ setup.js:104
(anonymous) @ angular.js:19916
completeOutstandingRequest @ angular.js:6111
(anonymous) @ angular.js:6390`

**Comment by brantje** [comment]
I think that's the problem then. Can you try with LE?

**Comment by adocampo** [comment]
Ok, I'll do a quick test and report back.

**Comment by adocampo** [comment]
I did try with the Firefox addon. No complaining about the INSECURE_RESPONSE. Perhaps Chrome/chromium are more sensible to that.

**Comment by brantje** [comment]
Chrome is indeed very strict with ssl and extensions. However, catching a SSL error in the extension is a pain. The request fails with error code `0` which is an undefined error >_>.

**Comment by adocampo** [comment]
I'm gonna try to install a LE certbot into my NC docker, hopefully it will work and we can clear up any doubt.

**Comment by adocampo** [comment]
Installing a LE certificate works as expected!
