### ISSUE TITLE
After generating and saving password, dialog should disappear

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#160]
### Steps to reproduce
1. Generate and save new login passwords.

### Expected behaviour
Dialog disappears and (thus) indicates saving finished.

### Actual behaviour
The "Saving…" stays there. Dialog stays open. Nothing happens.

### Configuration
**Browser**: Firefox 54

**Extension version**: 2.0.3 

**Nextcloud version**: 12

**Comment by brantje** [comment]
Duplicate of #157

**Comment by rugk** [comment]
Ah, ups…
