### ISSUE TITLE
Change source line to apply l10n fix 

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/passman-webextension#168]
https://github.com/nextcloud/passman-webextension/blob/e1397dc5edb87bb98e31d407353805a79facf7e2/_locales/en/messages.json#L375

Please change "urls" to "URLs"

**Comment by brantje** [comment]
Can your make a PR for this? Don't forget to sign it.
Thanks :+1:

**Comment by comradekingu** [comment]
https://github.com/nextcloud/passman-webextension/pull/171

**Comment by rakekniven** [comment]
@brantje as already mentioned in other PRˋs I am not able to sign my commits like you want. So I start to file issues.
