### ISSUE TITLE
Password picker position

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#174]
### Steps to reproduce
1.  Go to [https://my.n26.com/](https://my.n26.com/ )
2. Click on the form icon in password field

### Expected behaviour
Password picker shows up under the password field

### Actual behaviour
Password picker shows up in the top of the page

### Configuration

**Browser**: Chrome 60 / Firefox developer 

**Extension version**:  Latest commit on master

![screen shot 2017-08-21 at 21 45 36](https://user-images.githubusercontent.com/7913565/29546448-30bcc014-86ba-11e7-94e4-9e59987c1986.png)

**Comment by brantje** [comment]
This is fixed in next update.
