### ISSUE TITLE
Form icon isn't shown in email field

### ISSUE THREAD

**Issue by dardelet** [nextcloud/passman-webextension#175]
### Steps to reproduce
1. Go to https://my.n26.com/

### Expected behaviour
See a form icon in the email field

### Actual behaviour
No form icon in the email field

### Configuration

**Browser**: Chrome 60 / Firefox developer 

**Extension version**:  Latest commit on master

**Comment by nodauf** [comment]
It is really strange, in the form for login there are 2 input for password (one hidden) and one input for email and one input text (hidden)
![image](https://user-images.githubusercontent.com/7670696/29546716-f305dc88-86c3-11e7-9ce9-ea936d643527.png)
The first two are fill by passman but the others one are left blank.
