### ISSUE TITLE
passwords number seen on new tab

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#176]
I do not know how to name this issue. On passman icon, when opening a new tab or while loading a website from a new tab, appears a number like if it was the number of passwords stored for a site.
The weird thing besides a number is shown is that numbers is too high to be the number of stored passwords (787) for a single site but too low to be the total number of passwords stored on the vault (1019). Once the site is loaded, the right number of stored passwords for that site is shown unless the tab is in blank, in that last case, the weird number shows.
As a curiosity, it shows always the same number (787), so I guess it's showing something not random.
 
### Steps to reproduce
1. Open a new tab in blank or click on a link to be opened on a new tab
2. Passman icon shows a number (787) until the website is completely loaded.
3. Once the site is loaded, the number change to the right stored passwords, unless no site was loaded at all (i.e.: blank tab).

### Expected behaviour
No number at all should be shown until the website is fully loaded.

### Actual behaviour
A number is shown while loading or on a new blank tab. 
![Like this](http://i.imgur.com/9kDubQc.png)

Not all the passwords stored on the vault
![Like this](http://i.imgur.com/uPDcTEx.png)

### Configuration
**Operating system**: Arch Linux 64bits

**Browser**: Firefox 55.0.2

**Extensions that might cause interference**: none

**Passman version**:  2 .1.4

**Extension version**: 2.0.3

**Nextcloud version**: 12.0.2

**Comment by brantje** [comment]
@adocampo Is this still happening? I don't see it with version 2.0.3
![image](https://user-images.githubusercontent.com/2758767/32133729-3a44c39e-bbde-11e7-8111-12fefbadfe7a.png)

![image](https://user-images.githubusercontent.com/2758767/32133731-3e2727e0-bbde-11e7-9e7a-2d50f62c53de.png)

**Comment by adocampo** [comment]
Don't seem so. We can close this :)
