### ISSUE TITLE
Making a XUL version

### ISSUE THREAD

**Issue by nado** [nextcloud/passman-webextension#177]
Hi,

Would you consider making a XUL extension for browsers like Pale Moon ?
Web-extensions are not supported in this case.

TBH, I have no experience in browser extensions development, and thus no idea about the level of work needed here.

**Comment by brantje** [comment]
No, XUL is deprecated. Converting the extension to XUL is a lot of work. 
And because it's for just 1 browser who doesn't use new technology's i won't support it.

**Comment by nado** [comment]
Pale Moon doesn’t intend to "update" to webextensions as this framework doesn’t give access to a low level API.

Too bad for me then, maybe in 5 years I’ll have learned to XUL it myself :)
