### ISSUE TITLE
Feature: Add 2FA after entering master password

### ISSUE THREAD

**Issue by gpoudrel** [nextcloud/passman-webextension#180]
Hello,

it would be nice to add 2FA when entering extension master password. So even if someone "guesses" your password you will have an extra security.

**Comment by brantje** [comment]
Will not be implemented because, that would defeat the purpose of 2fa. 
A human action is required to confirm it. Passman provides the OTP, you only need to copy it.

**Comment by iudex-** [comment]
Sorry, could you please elaborate on this?
How would I use passman with a 2fa protected nextcloud account?
For the moment I don't see any way. But I think this is what @gpoudrel was hinting at.
I also can't see how passman providing OTP is of any use in this case.

**Comment by brantje** [comment]
If you use Nextcloud with 2FA, you can use a App password. 
Like this:
![image](https://user-images.githubusercontent.com/2758767/34045074-c73bd780-e1a7-11e7-815d-b5c7b2066f7a.png)
For more information about app passwords please refer to the Nextcloud docs.

**Comment by iudex-** [comment]
oh yeah, did not even think of that possibility...
tanks a lot! :)
