### ISSUE TITLE
Set breakpoints disturb web devs

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#183]
### Steps to reproduce
1. Open any site, where you have passwords saved for.
2. Press F12 to open the console.

### Expected behaviour
Nothing special should happen.

### Actual behaviour
Some breakpoints are set in jQuery Sizzle and more. So to make any use of the console and to make JavaScript continuing to execute, you have to press "continue" in the debugger multiple times.

### Configuration
**Operating system**: Linux

**Browser**: Firefox 55

**Extension version**: 2.0.3

**Nextcloud version**: 12
   
#### Browser log
nothing

**Comment by brantje** [comment]
Break points are local afaik.

**Comment by rugk** [comment]
So what? (does that mean?)

**Comment by brantje** [comment]
That means it's not a passman webextension problem

**Comment by animalillo** [comment]
@rugk that means that you have set that breakpoints on your local machine, it's not something on the code of the extension
