### ISSUE TITLE
Can't get value of custom password field

### ISSUE THREAD

**Issue by noplanman** [nextcloud/passman-webextension#184]
### Steps to reproduce
1. Add any custom field of type "Password".

### Expected behaviour
I should be able to access the entered custom password.

### Actual behaviour
There is a password input with "*" only, which doesn't allow copying.

### Configuration
**Operating system**: MacOS
**Browser**: Waterfox 55.0.2
**Extensions that might cause interference**: -
**Passman version**: 2.1.4
**Extension version**: 2.0.3
**Nextcloud version**: 12.0.3

**Comment by brantje** [comment]
Uhm not really, the extension has been made to make use of the `password` field.
Custom fields with type password are not supported. This because, when an credential has multiple password custom fields, how does the extension knows which to use?

Feel free to open a feature request for supporting password custom fields.

**Comment by noplanman** [comment]
Hi @brantje, that's not what I mean.

What I mean is, if you save a password as a custom field, there is literally no way of accessing it through the extension.

To explain my use-case: API Tokens!
When you have an account for a service that has an API, normally a separate API token is to be used for that service. This token must be treated like a password (for obvious reasons). So I add that as a custom password field. Now, I'd like to access this token from time to time, but I can't do this through the extension, as there is no way.
This really should be possible, as it makes the custom password fields quite useless otherwise 😕 

Unless I've totally misunderstood the usage of those custom password fields.

Of course a feature could be added to include custom password fields to be used as login passwords, but that's not the issue here.

**Comment by brantje** [comment]
I think your issue is solved with this: https://github.com/nextcloud/passman-webextension/issues/138#issuecomment-339610982

**Comment by noplanman** [comment]
I don't think so, as I think that does this, which is not my "issue":

> Of course a feature could be added to include custom password fields to be used as login passwords, but that's not the issue here.

What I need is a way to simply copy the contents of a custom password field, the same way that a normal password can be copied, by clicking the little copy icon next to it.

My problem isn't using the custom password field for the autofill feature, but to literally get the content of it, as this password may be needed on different sites or applications.
At the moment I always have to login to my Nextcloud instance and open the password manager there, which is just very cumbersome 😕 

Does that explain it better?
