### ISSUE TITLE
Does not work on the bank site

### ISSUE THREAD

**Issue by pyziak84** [nextcloud/passman-webextension#186]
Extension does not work on the bank site: https://online.nestbank.pl/bim-webapp/login
The login and password are still empty.

### Configuration
**Operating system**: Windows 10 x64
**Browser**: Chrome
**Passman version**: 2.1.4
**Extension version**: 2.0.3
**Nextcloud version**: 12.0.3

**Comment by brantje** [comment]
Their strange form messes up the detection. 
![image](https://user-images.githubusercontent.com/2758767/31164740-b1400d36-a8e8-11e7-980b-e6a1344983c0.png)
Nothing we can do about this. 
Seems they do this on intention. (look at the input names)

**Comment by iudex-** [comment]
The fix for nestbank breaks all two step login processes.
ie. paypal, google, amazon, ...

see #226
