### ISSUE TITLE
Chrome - Custom Fields not working

### ISSUE THREAD

**Issue by anonymous-one** [nextcloud/passman-webextension#188]
Perhaps I am doing something wrong, but I cannot for the life of me get custom fields to work.

A) I enter both the label (eg: <label) and the id / name  of the input element (eg: <input type="text" id="someElement> into the passman interfaces (via nextcloud). I enter both, just to be sure. I have tried all sorts of combinations.

B) Changes are picked up by the extension. Custom field data is shown in the custom fields tab for the password entry in the extension.

C) Passman does not auto fill the custom fields.

---

This is a bit of an issue, as about 10-20% of the websites I would like to store the passwords for use a form of <input element that is NOT picked up by passman as a username field and thus, I have to type the username in.

---

Am I doing something wrong or is this expected behavior?

EDIT : A good example of this is : https://login.skype.com/login | As far as I can tell there is no way to use passman+chrome to autofill the username field presented by the skype login page.

**Comment by brantje** [comment]
Filling custom fields is not supported. This would be a plain to implement. 
But i like the idea of using the field id's for filling. But what if there are no id's existent?
Matching by label would become very CPU intensive, as i have to loop every credential, then every custom field to compare it, then look up the label and find input field.

Since passman doesn't find the inputs, can you provide me the html of those websites?
The 'algorithm' for finding forms is easy to understand, and you can find it [here](https://github.com/nextcloud/passman-webextension/blob/master/js/lib/findForm.js)

**Comment by anonymous-one** [comment]
The <label comment / idea was just me trying to figure out if I could get the auto fill to work. I agree, no need to go that route.

Also agree, a simple id tag based auto fill would be sufficient. This would probably solve quite a few login issues were there are 3 (or more) input field based logins. Eg: Quite a few banks use this, username + password + some sort of pin. Or even issues where the algo does not pick up the correct fields.

---

Ok, so basically the algo finds the password field and works backwards assuming the previous <input type="text" is the username field...

---

Sure enough, from one of my banks:

`<input type="text" name ="preventAutoPass" id="preventAutoPass" style="display:none" />`

So yeah, the have a text field labeled prevent auto pass specifically for this reason... Grrr... Ok so that takes care of that one...

---

Another one that does not work is when the username field is type="number". I am unsure how common it would be to have the field previous type="password" to be type="number" but not the username... I suppose that is a decision for the developers to decide if the want to assume the previous type="number" field can safely be assumed to be the username field.

---

But to summarize, all of this could be solved via using the custom fields + auto fill in an id based way ;)

**Comment by brantje** [comment]
The webextension should ignore strings like `preventAutoPass` or such. 
What banks often do make a crazy form to mess with the detection algorithms.

Well,  what would be possible, when a custom field starts with an `#` the extension knows that it's an id, an it needs to fill it on the current page.

**Comment by anonymous-one** [comment]
I'll have a look at the code this evening and see if I can make the changes.

**Comment by anonymous-one** [comment]
Alright so I have made the changes... To be honest, I have never submitted to github before... The changes are fairly straight forward so maybe you can merge them...

The behavior is just as you mentioned:

A) In Nextcloud: Set the "label" for a custom field to "#ELEMENTID", enter a value.

B) Then ELEMENTID will be auto filled with the stored value.

I put this together fairly quickly, but it should be ok.

---

js/background/inject/inject.js :

`function enterCustomFields(login,settings) {
		var customfields;
		var customfieldpattern=/^\#(.*)$/;
		
		/* parhaps wise to try / catch this as this is non essential and no reason to abort previous processing */
		try{
			/* do we have custom_fields for this entry */
			if(login.hasOwnProperty('custom_fields')&&login.custom_fields.length>0){
				/* yes we do */
				customfields=login.custom_fields;
				/* iterate over all the custom_fields values */
				for(var i=0,len=login.custom_fields.length;i<len;i++){
					/* does this custom field label begin with a hash? */
					if(customfieldpattern.test(login.custom_fields[i].label)){
						/* set variable elementid to whatever element we are trying to auto fill */
						var elementid=customfieldpattern.exec(login.custom_fields[i].label)[1];
						/* does the element we are trying to auto fill exist AND is it either a text / number or password type? */
						if($j('#'+elementid).length&&($j('#'+elementid)[0].type=='text'||$j('#'+elementid)[0].type=='number'||$j('#'+elementid)[0].type=='password')){
							/* set the element value to the value returned by own/nextcloud */
							$j('#'+elementid).val(login.custom_fields[i].value);
						}
					}
				}
			}
		}
		catch(e){
			if(settings.debug){
                console.log('While attempting to auto fill the custom fields the following exception was thrown: '+str);
			}
		}
	}
`

Also under enterLoginDetails(logins[0], false);:

`enterCustomFields(logins[0], settings);`

**Comment by brantje** [comment]
We'll continue in #138
