### ISSUE TITLE
Updated custom field auto fill wiki

### ISSUE THREAD

**Issue by anonymous-one** [nextcloud/passman-webextension#197]
Still new at this github and am not sure how to edit the wiki, here is a wiki I typed up explaining the whole custom field auto fill process.

Feel free to update the main one on here.

---

Any custom field with a label that begins with a hash (#) is searched for on the website you are visiting and auto filled if found. The search is done via the id or name properties. The website you are visiting must of course have an entry in your list of passwords. Standard Passman URL checks all apply. This can be used for websites that require an additional field to be filled (for example many banks require 3 fields to be filled to login) or websites where for whatever reason the username and password fields are not detected properly by the Passman extension. Additionally, input elements are first searched via the id property, and if not found, an additional search is done for elements where a match is made via the name property. As mentioned, this can be used to auto fill websites where Passman is unable to detect the correct username and password fields as the custom field auto fill process is completed regardless if Passman finds the login form. Last but not least, the element to be auto filled must be of type text, number or password.

**Example 1:**

URL : https://www.example1.com/
Somewhere in the page body : ```<input type="text" id="pinCode"/>```

You would then create a password entry that looks as follows:
URL : https://www.example1.com/
Username : Your username (This will be used if Passman detected a username + password)
Password : Your password (This will be used if Passman detected a username + password)
Custom Fields :
Label - #pinCode
Value - Value to be filled in

Result : Passman will auto fill input element with id pinCode with whatever value you set.

**Example 2:**

URL : https://www.example2.com/
Somewhere in the page body : ```<input type="text" name="pinCode"/>```

You would then create a password entry that looks as follows:
URL : https://www.example2.com/
Username : Your username (This will be used if Passman detected a username + password)
Password : Your password (This will be used if Passman detected a username + password)
Custom Fields :
Label - #pinCode
Value - Value to be filled in

Result : Passman will auto fill input element with name pinCode with whatever value you set.

---

**Comment by brantje** [comment]
Thank you, updated the wiki.
