### ISSUE TITLE
Bug - TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by anonymous-one** [nextcloud/passman-webextension#198]
Found a bug that appears on HP ILO4 logins. This is the KVM system on HP based servers.

Here is a copy paste from the console:

Error in event handler for (unknown): TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/domchanged.js:14:17
    at C_Promise.finally (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/background/inject/inject.js:386:21)
    at C_Promise.call_then (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/promise.js:43:25)
    at C_Promise.<anonymous> (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/API/runtime.js:89:26)

(index):1 points to domchanged.js:

```
var observeDOM = (function(){
    var MutationObserver = window.MutationObserver || window.WebKitMutationObserver,
        eventListenerSupported = window.addEventListener;

    return function(obj, callback){
        if( MutationObserver ){
            // define a new observer
            var obs = new MutationObserver(function(mutations, observer){
                if( mutations[0].addedNodes.length || mutations[0].removedNodes.length ){
                    callback();
                }
            });
            // have the observer observe foo for changes in children
            obs.observe( obj, { childList:true, subtree:true });
        }
        else if( eventListenerSupported ){
            obj.addEventListener('DOMNodeInserted', callback, false);
            obj.addEventListener('DOMNodeRemoved', callback, false);
        }
    };
})();
```

Here is a sample URL, not this is not my KVM as I do not want to expose it... But the issue appears on this URL just as it does on my KVMs:

https://grandmastreams.me/

Edit : This error (in the js console) appears regardless if you have a password entry saved for the website or not. So a simple visit to the above (or any HP ILO4 login) will produce this error in the console. Once the error appears, Passman stops.

**Comment by anonymous-one** [comment]
Stackoverflow (a couple of threads) point to wrapping the observeDOM function in a ```$(document).ready(function () {```, essentially waiting until the DOM is ready.

I have not looked in deeply as to if this will cause any issues... @brantje want to chime in?

**Comment by brantje** [comment]
Strange thing is that we already wait for the document to complete loading:
![image](https://user-images.githubusercontent.com/2758767/32143529-ea236d48-bcaa-11e7-8d6d-f69f59ac2156.png)

**Comment by brantje** [comment]
Seems that the ilo site uses framesets

**Comment by anonymous-one** [comment]
Ah ok...

Also, turns out I had my #label custom field values set incorrectly... Was missing an upper case I on usernameInput... When fixed, even though the console shows the error, they are auto filled correctly :)

I suppose we can close this. Although some investigation regarding why the exception is thrown might be good ;)

**Comment by brantje** [comment]
Exception is thrown because they don't use a body tag.

**Comment by trushamandaviya** [comment]
@brantje You can try to loop through it and create an observer for each element.

May be like this: 
var targets = document.getElementsByTagName("formCaseAssignee_@Model.FieldId");
let observer = new MutationObserver(observerCallback);
Array.from(targets).forEach(target => {
  observer.observe(target, {
    attributes: true
  });
});

function observerCallback(mutations) {
//Do something
}
