### ISSUE TITLE
Setting it up

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-webextension#2]
Actually this a question.
As i've never done a chrome / firefox extension before, i don't really have a clue how to set it up properly.

Maybe a chrome extension developer can shine some light on this?

**Comment by tapir** [comment]
Here is 2 tutorials that are perfect for starting:
1- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_second_WebExtension
2- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Implement_a_settings_page

First one implements a toolbar icon and a popup.
Second one implements a settings page.
All in HTML and CSS.

I'll try to implement some simple UI for both.

**Comment by tapir** [comment]
When I look at the passman API I see that there is no way to query a password by its URL and that all URLs are encrypted. So in order for the extension to fill in the password of a website:

1- Get all the credentials in all the vaults
2- Decrypt all the credentials
3- Find out if the URL matches current website
4- Fill in or list possible credentials

This seems like the worst possible way of doing it.

Would it be possible to make passman not encrypt the URL and allow API to query by URL?

**Comment by brantje** [comment]
Yes would be possible to have url unencrypted. Don't know what @animalillo thinks about this.

**Comment by tapir** [comment]
Another inconveniance for the user of the plugin would be to enter the passwords for all the vaults. It might be a good idea to make the plugin work only on a single vault.

**Comment by brantje** [comment]
This is what i have for now (just a simple html + angular page):
![image](https://cloud.githubusercontent.com/assets/2758767/22404935/2594a26c-e63b-11e6-81bc-7cd9fa9cbf35.png)

**Comment by brantje** [comment]
Small update
Saving setting works (currently saving everything as plain text, including vault key....).
Fetching credentials in the background works.
Looking up credentials works (as seen in the screenshot)
![image](https://cloud.githubusercontent.com/assets/2758767/22408575/9e1b44a8-e67b-11e6-9f30-25263b4cc63e.png)

**Comment by brantje** [comment]
![image](https://cloud.githubusercontent.com/assets/2758767/22510224/6f5a570e-e891-11e6-8cbc-5b8f42cade9f.png)
Another update =)

**Comment by tapir** [comment]
Looking good. How does it match the website now? Does it decrypt all the vaults and credentials?

**Comment by brantje** [comment]
It decrypts 1 vault at the moment. 
Maybe more in the future.
Looking up the credential is done locally, since keeping the url unencrypted is not an option.

**Comment by tapir** [comment]
Perfect can you commit what you have so that I can test it for firefox?

**Comment by tapir** [comment]
Also how about changing the repo name to passman-webextension?

**Comment by brantje** [comment]
@tapir If you have telegram then you're welcome to chat with us at https://t.me/passman_dev, atm we don't have our own slack / mattermost, since we don't have that many members.

**Comment by brantje** [comment]
Closing, extension is on it's way to release.

**Comment by animalillo** [comment]
think this is relevant here:

**Comment by brantje** [comment]
You mean this:
![image](https://cloud.githubusercontent.com/assets/2758767/22776943/f505d45c-eeb1-11e6-90d5-60193b5e95a9.png)
