### ISSUE TITLE
Publish update to Chrome Store

### ISSUE THREAD

**Issue by jkaberg** [nextcloud/passman-webextension#20]
Would you guys mind publishing a new update @ Chrome store?

The current one is 1.0.1 dated 10 february

**Comment by brantje** [comment]
Will do this weekend, just got started at my new job =)

**Comment by jkaberg** [comment]
Great, thanks @brantje and congratulations on the new job! 😄

**Comment by jkaberg** [comment]
bump @brantje

**Comment by brantje** [comment]
Relax, we have personal lives too ;).

**Comment by brantje** [comment]
Update will be pushed this weekend.
