### ISSUE TITLE
Passman window closes when clicking into settings or unlock password field

### ISSUE THREAD

**Issue by kkremitzki** [nextcloud/passman-webextension#206]
Hi, this is a bit of a strange issue as I can't replicate the scenario on a different computer, but it has happened before, so I decided to report it.

The extension was working fine (and does work fine on another machine running same OS, same browser, same Nextcloud server, etc), but the issue started when I clicked the lock icon. Whenever I tried to unlock my vault and clicked into the password field, the Passman popup would close.

I tried removing my profile (I just did `rm -rf ~/.mozilla`, `rm -rf ~/.cache/mozilla`) and rebooting, but the behavior persists with a clean profile with no actions taken besides installing the Passman extension. This time, however, it's when I click into the password field on the server settings.

At this point I'm not sure how to proceed in even troubleshooting the problem, so I'm hoping for some help. Thanks.

### Steps to reproduce
1. Click extension icon on browser toolbar
2. Begin to unlock vault or enter server settings
3. When the password field is clicked or tabbed into, extension window closes

### Expected behaviour
I should be able to type my password.

### Actual behaviour
Since the Passman window closes, the extension will either stay locked or the server settings cannot be entered.

### Configuration
**Operating system**: Arch Linux

**Browser**: Firefox Nightly

**Extensions that might cause interference**: Behavior persists with only Passman installed

**Passman version**: 2.1.4

**Extension version**: 2.0.4

**Nextcloud version**: 12.0.3
   
#### Browser log
No message is generated in the console.

**Comment by brantje** [comment]
Do you mean clicking outside this window:
![image](https://user-images.githubusercontent.com/2758767/32414347-e964df20-c224-11e7-8559-f1bb62d506f8.png)
If yes. Well we can't do much about it since that's the way how extensions work.
Keeping the window open is possible with right click in the panel and then inspect element.

**Comment by kkremitzki** [comment]
Sorry, that's not what I'm talking about. The issue is that after I clicked the lock icon in your screenshot, I would proceed to here:

![passman](https://user-images.githubusercontent.com/4983176/32422064-980a3c94-c263-11e7-8d30-fb5a748a5e63.png)

Then, upon clicking into the password input area, the extension window would immediately close.

I removed my Firefox profile, made a new one, added the Passman extension, and when I proceeded to the screen with server settings, the same behavior would happen with the password input area there, whether I clicked into it or tabbed into it.

**Comment by brantje** [comment]
Strange, i'm using firefox too and didn't see this problem yet.

**Comment by kkremitzki** [comment]
I haven't been able to reproduce it since reinstalling my OS on the machine it was occurring, although I had seen it twice on separate machines--if you felt like closing this as not reproducible I wouldn't mind. It doesn't look like there's been any other reports of it.
