### ISSUE TITLE
Sync removes password generated with the extension

### ISSUE THREAD

**Issue by floreal797** [nextcloud/passman-webextension#207]
Hi,

Since I upgrade the extension to 2.0.4 version, when I add a password through the password generator, it appears on the extension menu. But if I go to my nextcloud and I search for it, it's not present. And when I sync passwords, it disappeared from the extension and the password is lost!!

It is not every time, but still often... It's a big and critical bug, isn't it?

### Steps to reproduce
1. Add new password throug form on password field (add new website form)
2. The password entry appears on the list in extension menu (but the number does not change)
3. Sync
4. Few seconds after, the entry disappears

### Expected behaviour
The new password is sent to the server and saved

### Actual behaviour
The new password is deleted from the client on sync and never saved to the server. But it doesn't appears each time, but often.

### Configuration
**Operating system**: Linux 64 bits

**Browser**: Chromium 62.0.3202.75

**Extensions that might cause interference**: None

**Passman version**: 2.1.4

**Extension version**: 2.0.4

**Nextcloud version**: 12.0.3

**Comment by brantje** [comment]
Did you fill in a label, otherwise this issue looks like #204

**Comment by floreal797** [comment]
Yes, I set a label.

On amazon login page, if I use the form to add a new website, the bug appears each time. I fix my description because the number on the extension does not change. The entry appears, and after sync it disappears. And it's never sent to the server.

**Comment by brantje** [comment]
@floreal797 What amazon site? You've got a link?

**Comment by floreal797** [comment]
The french amazon website sorry,
https://www.amazon.fr

Click on "Identifiez-vous" and then on the form try to add a new website to passman.

**Comment by brantje** [comment]
Well, you need to fill in a label. A fix for that is being worked. on

**Comment by floreal797** [comment]
"Étiquette" in French is "label" in english, right? I fill it, but I have the bug anyway...
