### ISSUE TITLE
Feature suggestion: Manual search for entries

### ISSUE THREAD

**Issue by astroneer** [nextcloud/passman-webextension#21]
**Issue:**
Sometimes a host slightly changes the URL/path of a login page.
This can make passman fail to automatically find the entry for this host, resulting in an empty list.
Knowing that I have an entry, I have to login to nextcloud/owncloud to search the entry there, correct the URL manually, refresh passman's credential list and I'm back in business.

**Proposal for a new feature:**
Offer a manual search for entries.
When clicking on passman's icon an optional search field could allow to enter a text to search for entries (i.e. bypassing the automatic URL/path matching).
The resulting list could be displayed the same way as the current automatic URL matching does (and selectable by the user).
As an additional feature passman could realize that this manually picked entry does not fit to the current URL/path and offer to update the URL/path of the stored entry with the current URL/path.

**Comment by brantje** [comment]
Do you have example sites that do this?

**Comment by astroneer** [comment]
It's not something that happens regularly on specific sites. Probably only if hosts do a re-organisation of their company, including an update of their web sites.

E.g. just today I observed this issue on following site:
I didn't log into this site for a while and the stored URL for my login was:
https://spdns.de/index/login/
After entering this URL in the browser the host did an automatic URL correction to the new URL:
https://www.spdyn.de/index/login/
As a consequence passman did not show any hit for this new URL.

So I logged into nextcloud, searched for the entry and replaced the old URL by the new one. After refreshing the credential list and reloading the login site, passman found the entry.

I encountered this a few times during the last weeks. I imported all my keys from keepass and tested passman. I had a few really old logins which I didn't use for a long time (and during this long time the URLs have changed).

It's definitely not an issue people encounter every day (and it's not a show stopper), so I guess it would be fair to wait if other users would enjoy such a new feature. Just to ensure you don't waste your time just for me... BTW: Thanks for the great app :-)

**Comment by brantje** [comment]
Than the problem is that the url finder doesn't match with www.
To tackle that problem i can add a `Ignore www subdomain` option, so you don't need to search.

**Comment by astroneer** [comment]
I'm afraid they did not simply add a www to the URL, see here without www:
spdns.de/index/login/
spdyn.de/index/login/
...dns... -> ...dyn...

**Comment by brantje** [comment]
Preview:
![image](https://cloud.githubusercontent.com/assets/2758767/24832141/3a4955d2-1ca9-11e7-981e-2d0c9597f84c.png)
Only thing left is updating the url of the selected credential.

**Comment by astroneer** [comment]
Preview looks great :-).
Thanks for the update and the (weekend) time you spend on this.
