### ISSUE TITLE
Always shows connection error, but works

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#212]
### Steps to reproduce
1. Account setup. Start browser. Log in.

The server is running in the same LAN as the client (and is accessible), so it is virtually impossible that it there is a timeout.

### Expected behaviour
No error.

### Actual behaviour
Shows notification:
> **Error**
> Error connecting to server (Error: Connection timeout)

But it still works, after some seconds when it has downloaded the passwords. 

### Configuration
**Operating system**: Linux

**Browser**: Firefox 56

**Passman version**: 2.1.4

**Extension version**: 2.0.4

**Nextcloud version**: 12

**Comment by brantje** [comment]
How about self signed certs? Those will be rejected by chrome / firefox. No way to accept them

**Comment by rugk** [comment]
No, just to stress it: **It works** after a few seconds. It just shows this error message, claiming there is an error. Maybe there even is a valid error, but the ad-on retries it after 2 seconds or so… don't know.

**Comment by jzielke-nli** [comment]
Confirming the problem.

**Comment by AnXh3L0** [comment]
Are you running any local proxy or DNS caching like Pi-hole?

**Comment by rugk** [comment]
No, no proxy, but DNS caching likely happens at router level. (Just usual DNS sever though, it also resolves the domain passman uses for connection to nextcloud)

**Comment by brantje** [comment]
Timeout error was increased a few releases ago, is this still an issue?

**Comment by brantje** [comment]
I'll close it for now, feel free to open a new issue if the problem still exists.
