### ISSUE TITLE
Support for Nextcloud double authentification

### ISSUE THREAD

**Issue by koug44** [nextcloud/passman-webextension#214]
### Expected behaviour
Entering URL and login informations should connect to my Nextcloud provider, or at least asking me about providing an OTP token

### Actual behaviour
The login fails with  [401] Unauthorized HTTP error

### Configuration
**Browser**: 
Firefox 57

**Passman version**: 
2.1.4

**Extension version**: 
2.0.4

**Nextcloud version**: 
12.0.3

**Comment by brantje** [comment]
You need to use a [app password](https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices).
Then everything will work fine.

**Comment by koug44** [comment]
Wow, what I was thinking… of course, it’s working now. I’m closing the report
