### ISSUE TITLE
Where clear ignored URLs?

### ISSUE THREAD

**Issue by poggenpower** [nextcloud/passman-webextension#215]
Hi,

had added an URL to the ignore list, because Passman filling out form field on a sub page. 
But now I want to remove this URL from the Ignore list, to get Passman working un that URL again.

Didn't find a place where I can maintain this list.

Passman extension 2.0.4
Passman 2.1.4
Chrome 62.0.3202.89
Nextcloud 12.0.2
Mac OS

May be I am blind.

Thanks
 Thomas

**Comment by brantje** [comment]
1. Go to settings
![image](https://user-images.githubusercontent.com/2758767/32878376-102e3866-caa6-11e7-80e5-be0a511c1d50.png)
2. A list shows up, click on the trash icon to delete a entry.
![image](https://user-images.githubusercontent.com/2758767/32878411-3342202e-caa6-11e7-9dd2-c9e8cdcde4ae.png)

**Comment by poggenpower** [comment]
Thanks a lot. Was blind!
