### ISSUE TITLE
Textarea for Freehand Notes 

### ISSUE THREAD

**Issue by compumatter** [nextcloud/passman-webextension#217]
## Feature request

**User type**: Logged-in or public user
Public user (ie chrome, firefox extensions)
**User level**: Beginners, intermediate or advanced
Advanced
### Description

The textarea / notes information IS one of the fields in Nextcloud that is maintained / viewable / editable as a 'logged in user'.  However, there is no access to this data when using the passman extension.  
### Benefit / value

This is inherently needed information since the plugin contains the data we should be able to see it here.
### Risk / caveats

None that I am aware of
### Sponsorship

**Are you a developer willing to implement this feature?**: yes/no
No
**Can you sponsor the development of this feature or do you know someone who can?**: yes/no
I would contribute 50.00 towards its implementation
![lasptass](https://user-images.githubusercontent.com/121611/33145032-df6d1bd4-cf73-11e7-9038-f342bce22bb6.png)

**Comment by brantje** [comment]
Thank you for moving the issue.
You have a good point it's missing in the extension, will spend some time on it this weekend, and try to release it.

**Comment by compumatter** [comment]
I appreciate you recognizing the value of it and being able to go after it so soon.

**Comment by benyanke** [comment]
Would also appreciate this in both the extension and web app core. Looking to move away from lastpass to this, if possible
