### ISSUE TITLE
chrome browser plugin not working

### ISSUE THREAD

**Issue by muralikodali** [nextcloud/passman-webextension#219]
chrome browser plugin is giving following response:

**Invalid response from server: [0] TypeError: Failed to fetch** 

throwing error with self-signed ssl certificate with which nextcloud is configured.

**Comment by brantje** [comment]
Hi @muralikodali 
Self signed certificates are not working with `fetch` this is a known chrome / firefox limitation.
The solution is import the cert to the browser.

**Comment by muralikodali** [comment]
Thanks for your suggestion.
After import of ssl server certificate in to Chrome browser,  plugin is working properly.
