### ISSUE TITLE
Key Icons are static when scrolling the screen in Nextcloud

### ISSUE THREAD

**Issue by a-dam-cook** [nextcloud/passman-webextension#22]
Thank you for building this extension, I've been using it for a couple of weeks, and I really like it.
One issue I have come across, is when I'm in Nextcloud, the key icons stay put on the screen when I scroll down the page.  

### Steps to reproduce
1. Login to Nextcloud
2. Open the "Personal" screen, or Admin -> Additional Settings
3. Scroll down

### Expected behaviour
- the keys should scroll with the screen and stay inside the username/password boxes

### Actual behaviour
- the keys stay in the same absolute spot on the screen, while the page scrolls beneath

### Configuration
**Operating system**:   
  Windows 7
   
**Browser**:   
  Chrome
  
**Passman version**:    
   1.01, also installed the latest commit (I think 1.02) in developer mode and same results    
       
**Nextcloud version**:
   11.01

**Comment by brantje** [comment]
Fixed in 54a0229
