### ISSUE TITLE
Suggestion: Hotkey Down Arrow

### ISSUE THREAD

**Issue by benyanke** [nextcloud/passman-webextension#220]
I would like to propose that a hotkey be added (similar to the lastpass plugin) which displays the field-dropdown for passman when the field is in focus and the user presses the down arrow.

This allows easier keyboard navigation w/o mouse.

**Comment by brantje** [comment]
Hi there,
You can use alt + arrow down to activate the extension.

**Comment by benyanke** [comment]
Thank you!
