### ISSUE TITLE
Hikvision security camera login form doesn't get auto-populated

### ISSUE THREAD

**Issue by synthead** [nextcloud/passman-webextension#229]
### Steps to reproduce
This issue is reproducible on a Hikvision DS-2CD2035FWD-I, but it's very likely that most other Hikvision cameras use similar HTML and are also affected.

1. Ensure that login details are present for a Hikvision security camera.
2. Head to the camera's web UI.
3. Observe that login form doesn't auto-populated when form appears.

### Expected behaviour
Form should be filled in with login details automatically.

### Actual behaviour
Form remains blank after it appears.  Here's the login form for reference:

```html
<td class="login-m">
				<div class="login-part">
					<div class="line"></div>
					<div class="login-error">
						<div class="inputValidTip ng-hide" ng-show="szErrorTip!=''"><i class="error"></i><label class="ng-binding"></label></div>
					</div>
					<div class="login-user">
						<input type="text" class="login-input ng-pristine ng-valid" id="username" ng-model="username" maxlength="32" autocomplete="off" placeholder="User Name">
						<i class="icon-user"></i>
					</div>
					<div class="login-item">
						<input type="text" ng-model="password" class="login-input ng-pristine ng-valid ng-scope" maxlength="16" style="display: none;"><input type="password" class="login-input ng-valid ng-dirty" id="password" ng-model="password" maxlength="16" placeholder="Password" pigsney=""><span onselectstart="return false;" class="pigsney close" style="left: 210px; top: 7px; display: none;"></span>
						<i class="icon-pass"></i>
					</div>
					<div class="login-item bottom">
					    <span class="pwd-link ng-binding" ng-show="oCap.bSptGuidImport || oCap.bSptQAReset" ng-bind="oLan.forgetPwd" ng-click="forgetPwd()">Forgot password?</span>
						<button type="button" class="btn btn-primary login-btn" ng-click="login()"><label ng-bind="oLan.login" class="ng-binding" style="">Login</label></button>
					</div>
					<!--<div class="login-item anonymous" ng-show="anonymous">
						<span ng-bind="oLan.anonymous" ng-click="login('anonymous')"></span>
					</div>-->
				</div>
			</td>
```

### Configuration
**Operating system**: Arch Linux

**Browser**: Chromium 63.0.3239.108

**Extensions that might cause interference**: n/a

**Passman version**: 2.1.4

**Extension version**: 2.0.4

**Nextcloud version**: 12.0.3

**Comment by brantje** [comment]
The `<form>` tag is missing thus we can't recognize the form. Not much to about this.

**Comment by synthead** [comment]
I checked the HTML for a `<form>` tag and didn't see one.  I logged in and watched a GET request get submitted to `http://admin:censored@camera/ISAPI/Security/sessionLogin/capabilities?username=admin`.  

Pretty non-conventional indeed.  What do you mean by "Not much to about this?"  Are there limitations with Passman's extension where a `<form>` is currently required for the auto-login to be populated?  I'm happy to put a PR together.

**Comment by brantje** [comment]
Yea currently we scan form the form tags using a [form manager](https://github.com/nextcloud/passman-webextension/blob/master/js/lib/findForm.js).
It might be possible without form tags, but that will put more load on the cpu, and we try to avoid that. (See #225 )

**Comment by ivalome** [comment]
I face the same issue, where you able to solve it?

**Comment by ivalome** [comment]
web browser tell me this:
http://localhost/ISAPI/Security/sessionLogin/capabilities?username=admin 404 (Not Found)

**Comment by OS3DrNick** [comment]
You cant use localhost on you computer if you want to browse to your camera.
Seems unrelated so far. 
and seems to misshing the admin:password notation in front. 
Every camera and its possible sign in pages are different. so make sure it can work with this entire url.

**Comment by usha-manwani** [comment]
Did anyone resolved this issue or find any way? I am also stuck here. ISAPI issue while trying to login to HikeCamera

**Comment by ivalome** [comment]
Finally I got it work, the way I did was very simple, I fact I did not modify anything of code. It was just about setting up the correct version of the software what I used was S.O. Win 7 ServicePack 1, IIS (Version 7.5.76000.16385) and it only works on internet explorer(be sure to install de plugin that comes with the SDK). the version I use for IE is 11.0.9600.19507 and thats it, please if someone achive run it on linux tell me please    regards from Ivan Medina

**Comment by usha-manwani** [comment]
Yes.. It works with IE bydefault.. But with other browsers it gives the error mentioned above. I am in china currently so I have 360 and sogou browsers also to work with and they allow plugins. But they throw this error. I dont understand why one browser can allow it and not the other ones
