### ISSUE TITLE
deleted passwords are taken into account to calculate sum of credentials in database

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman-webextension#23]
### Expected behaviour
The extension should calculate the sum of the credentials of the database without the deleted ones

### Actual behaviour
extension takes the deleted passwords into account to calculate the sum of credentials in the database

### Configuration
**Browser**:   
       Firefox 51
  
**Passman version**:    
       2.1.1
       extension version: 1.0.3
       
**Nextcloud version**:
       11.0.2

**Comment by brantje** [comment]
Should be fixed in d2ed987c7d670d45fb97e68397e3d4bfbfc0e25b
