### ISSUE TITLE
Feature request - Quick Disable

### ISSUE THREAD

**Issue by kidmock** [nextcloud/passman-webextension#231]
It would be nice if I could temporary disable the password autofill on a site without have to go into extension settings.

On a couple occasions, not having this ability has bitten me. 

For one, in the NextCloud LDAP admin screen it copied my password into the RootDN password. Because this is not the password and Nextcloud doesn't have a "save" button it automatically changed the password in Nextcloud and broke my authentication.

If there is a better work around to temporarily disable autofill  or if this could be added as "Right Disable extension" feature. That would be fantastic.

Thanks,
KM

**Comment by poggenpower** [comment]
+1
This would be very helpful

**Comment by brantje** [comment]
We have a lock icon (right top corner), that locks the extension. Would that be sufficient?

**Comment by kidmock** [comment]
@brantje After using it for a bit longer I realized I could lock and unlock the extension. This does give the functionality I was looking for. This request can be closed. Thanks.
