### ISSUE TITLE
Subdomain ignoration

### ISSUE THREAD

**Issue by NastuzziSamy** [nextcloud/passman-webextension#232]
### Expected behaviour
The extension should make the difference between 2 subdomains of the same domain:
  - sub1.example.org: one login/password is configured
  - sub2.example.org: no one is configured

When login on sub2, should not propose the sub1 configuration.

### Actual behaviour
Do not make the difference between subdomains and propose the login/password configuration for all subdomains of the same domain if already set for one

### Configuration
**Operating system**: 
ArchLinux

**Browser**: 
Firefox Developer Edition 59.0b3 (64-bit)

**Extensions that might cause interference**: 
None

**Passman version**: 
2.1.4

**Extension version**: 
2.0.4

**Nextcloud version**: 
12.0.5

**Comment by violoncelloch** [comment]
Have you checked the settings of passman extension? There is a preference for this...

**Comment by NastuzziSamy** [comment]
Thanks, I just supposed it was automatic...
