### ISSUE TITLE
Manually saving a site in Firefox does not work

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/passman-webextension#239]
Manually saving a site in Firefox does not work.

### Steps to reproduce
1. Install Passman
2. Go to a site with a login form
3. Click inside the form, clisc save site, enter details

### Expected behaviour
Tell us what should happen
The site is saved in local cache then saved into the Passman server.

### Actual behaviour
The site is saved in local cache, but after a sync it is deleted from local cache and it is not saved on the server.

### Configuration
**Operating system**: 
Debian
**Browser**: 
Firefox 58
**Extensions that might cause interference**: 
?
**Passman version**: 
2.1.4
**Extension version**: 
2.0.4
**Nextcloud version**: 
13.0
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

Where can i capture the passman logs? Debug option is enabled in the passman extension.

**Comment by witte1000** [comment]
Hello,

I have the same issues,

OS:
Ubuntu 16.04.3
Browser:
Firefox 58.0.2 
Passman version:
2.1.4
Extension version:
2.0.4
Nextcloud version:
13.0.1

Kind Regards,

**Comment by jzielke-nli** [comment]
Duplicate of #221

**Comment by brantje** [comment]
^_ dupe of #221
