### ISSUE TITLE
A lot of websites don't work for auto fill

### ISSUE THREAD

**Issue by Matttter** [nextcloud/passman-webextension#24]
### Steps to reproduce
1. Install extension
2. configure
3. go to Amazon.fr / other sites (some simpler sites do work though!)

### Expected behaviour

It should auto fill passwords

### Actual behaviour

Nothing happens, there are keys in the form but no login data is filled, and the little number on the icon stays 0

### Configuration
**Operating system**:   Ubuntu, Windows 

   
**Browser**:   Chrome 56
   
   
**Extensions that might cause interference**:   
   
Ublock origin
   
**Passman version**:    
       1.0.3 (extension) 2.1.1 (server app)
       
**Nextcloud version**:
    11.0.2
#### Server log
<details>
<summary>Server log</summary>
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-03-19T09:19:42+0100

Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-03-19T09:19:42+0100
</details>

**Comment by jones4410** [comment]
Sure you stored the right url in the passman entry?
And there are some settings in the extension to ignore a different site path or a subdomain...

**Comment by Matttter** [comment]
For amazon.fr I put amazon.fr, and checked the ignore path or subdomain boxes. No dice...

**Comment by brantje** [comment]
Complex login forms (especially when they made with ajax), are currently not detected.
The extension doesn't listen to dom changes. I'm sure there would be a solution, but at the moment i don't have the time to implement it (personal life).

**Comment by Matttter** [comment]
Ok, got it. The thing is, the little key icons are there, so it must detect the login forms, it just doesn't seem to correlate the password entry and the website (the counter stays at 0). Does the counter only go up when it detects a login form?

**Comment by brantje** [comment]
Counter goes up when it finds credentials for the site.

**Comment by animalillo** [comment]
Exactly, counter only goes up if logins are detected. If you give us a few URLs where this happens we will try to detect a pattern and fix it once we get a little time

**Comment by Matttter** [comment]
I'd like to, but how can I do so privately?

**Comment by brantje** [comment]
In chrome you can debug extensions by going here: chrome://extensions/
In firefox, you have to load the unpacked extension.

**Comment by Matttter** [comment]
I know that, I mean how can I send you the URL's privately?

**Comment by animalillo** [comment]
Pm us on telegram i'm @wolfi

**Comment by brantje** [comment]
Tested with lasted master, both sites seem to work.

**Comment by Matttter** [comment]
For me amazon and google to give examples don't work, the counter doesn't go up. It's like it can't detect which website it's on? Really weird. Paypal works fine though, to give another example. 

Also you should probably change the manifest.json to point to the correct css

**Comment by brantje** [comment]
Amazon.fr works here without problems, with upcoming version you can search for credentials in the password picker. When you select a credential, it will offer to update it.

**Comment by Matttter** [comment]
Ok, what am I doing wrong then? http://i.imgur.com/zCDIoTC.png
http://i.imgur.com/mZfmh2i.png
This is what happens on amazon.fr. Same deal on google.com

**Comment by brantje** [comment]
It's not yet live on chrome store, will push it tormorrow.

**Comment by Matttter** [comment]
I've downloaded the latest source, and while the searching works, it doesn't do anything when I click on the results

**Comment by brantje** [comment]
Do any JS errors appear in the console? (Both: background page and current page)

**Comment by Matttter** [comment]
Ok, so it worked now, it filled the password (great! it's usable at least now). Then it offered to change URL (url change detected), which is also great... but then after it updates it doesn't actually detect it (the key icon still has a 0 on it)

**Comment by brantje** [comment]
And if you press the refresh icon in the extension?

**Comment by Matttter** [comment]
Nope still 0

**Comment by brantje** [comment]
Did it update the url in passman?

**Comment by Matttter** [comment]
Yes, definitely

**Comment by brantje** [comment]
Can you poke me on telegram @brantje

**Comment by brantje** [comment]
We had contact on telegram, the search function kinda solves the problem.
