### ISSUE TITLE
login and password fileds not recognised on certain sites

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/passman-webextension#249]
### Steps to reproduce
1. go to https://ib.postovnisporitelna.cz/prihlaseni

### Expected behaviour
Login and password field should either be pre-filled or at least have the blue shield icon on the right.

### Actual behaviour
Nothing. Seems like form fields are not recognised by the extension.

### Configuration
**Operating system**: Linux 64bit

**Browser**: Firefox 59.0.2

**Extensions that might cause interference**: none (all other disabled)

**Passman version**: 2.1.4

**Extension version**: 2.1.1

**Nextcloud version**: 13.0.0
   
#### Browser log

JavaScript console empty, network logs without any errors or warnings.

**Comment by brantje** [comment]
Form tag is missing thus the extension can't detect it.

**Comment by cptMikky** [comment]
... and that's the reason to close this issue?

**Comment by brantje** [comment]
Yes, sites without a `<form>` tag are currently not supported.

**Comment by cptMikky** [comment]
So when should I post this issue again?

(also, maybe some kind of manual field identification could help here, like "click to login field, click to pass field", or something like that; not sure if this is more passman or extension feature - as this would require either one to keep such metadata somewhere)
