### ISSUE TITLE
Toolbar style is being overwritten by page

### ISSUE THREAD

**Issue by rmbl** [nextcloud/passman-webextension#25]
### Steps to reproduce
1. Visit any page which overrides bootstrap buttons
2. Login with new (to passman) account

### Expected behaviour
Toolbar is using the intended style.

### Actual behaviour
Toolbar is using a combination of the page style and the intended style.

### Configuration
**Operating system**:   
Fedora 25
   
**Browser**:   
Chrome 57.0.2987.110
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    
1.0.1
       
**Nextcloud version**:
11.0.2

## Picture

![image](https://cloud.githubusercontent.com/assets/60907/24363723/f0052f6a-1310-11e7-8a37-01eb79ed49cd.png)

Prefixing the class names should easily prevent this.

**Comment by brantje** [comment]
Fixed in f957782
