### ISSUE TITLE
Doesn't input when site searched for

### ISSUE THREAD

**Issue by Jab2870** [nextcloud/passman-webextension#251]
### Steps to reproduce
1. Go to a login Form
2. Search For another site
3. Click on one of the options

### Expected behaviour
The credentials for the item clicked on should be inputted into the form

### Actual behaviour
Nothing

### Configuration
**Operating system**: 
Arch Linux

**Browser**:
Chromium 67.0.3380.0 (Developer Build) (64-bit) 

**Extensions that might cause interference**: 
N/A

**Passman version**: 
2.1.4

**Extension version**: 
2.1.1

**Nextcloud version**: 
13

#### Browser log
Nothing

</details>

**Comment by brantje** [comment]
I'll try to find some time this week to fix it.

**Comment by mfilser** [comment]
Hello,
is this bug still there or fixed?
It would be very nice if i could search for something and after click to auto-fill the form because i migrated my password to passman, but the URL is often not correct so i have to use the search function of this extension.

Thank you in advance,
Martin
