### ISSUE TITLE
Extension for Opera [$10]

### ISSUE THREAD

**Issue by mat-m** [nextcloud/passman-webextension#255]
Hello

I tried to install the chrome extension with the [Install Chrome Extensions](https://addons.opera.com/en/extensions/details/install-chrome-extensions), and I got warned that unregistered API were used.
When I tested it, it actually cannot autofill the fields.
Since Opera is baed on chromium, it seems the extensions API are quite similar. Could you have alook if building an Opera extension for passman is doable ?
There are other extensions which does autofill (e.g. https://github.com/belaviyo/keepass-macpass-helper)

Thanks.

**Comment by pratik2315** [comment]
Hey! is this issue open to work? I would like to work on this issue

**Comment by mat-m** [comment]
moved to keeweb, sorry
