### ISSUE TITLE
select one of multiple credentials for one web page

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/passman-webextension#26]
### Steps to reproduce
1. create 2 or more credential for one web site
2.
3.

### Expected behaviour
would like to select one of the credentials

### Actual behaviour
shows all credentials, but no select option

### Configuration
**Operating system**:   
ubuntu 16.04
   
**Browser**:   
   chromium
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    
       1.0.2
       
**Nextcloud version**:
   11.0.2
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brantje** [comment]
You can click on the key icon in an input field to get your accounts:
![image](https://cloud.githubusercontent.com/assets/2758767/24829436/ec89eed8-1c71-11e7-9bd8-5885ee7b3e6d.png)

**Comment by ferdiga** [comment]
Hm, I do not have key icons - probably because I still use google password vault?

**Comment by brantje** [comment]
What site are you trying to login to? Some site are kinda tricky to get the icons working.

**Comment by ferdiga** [comment]
ok - I get a key symbol in the URL - but the symbol is different to your screenshot - (and difficult to recognize)
it says "saved password for this site" - but I can not click on the one I need.

**Comment by ferdiga** [comment]
the key symbol is not easy to recognize - I prefer the one in the screenshot 
![image](https://cloud.githubusercontent.com/assets/6248560/24830929/340ce638-1ca0-11e7-8fae-4017ff55bd98.png)

**Comment by brantje** [comment]
The icon will be changed in the future to something better.
Workings will stay the same, an icon in the input field.

**Comment by brantje** [comment]
They key symbol is chrome's password manager not passman.

**Comment by brantje** [comment]
Icon has changed to make things more clear look for the Passman icon in a input field.
![afbeelding](https://cloud.githubusercontent.com/assets/2758767/24894963/f0ef6e26-1e8d-11e7-9a48-b724f5f11519.png)
