### ISSUE TITLE
can not save credentials

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/passman-webextension#27]
### Steps to reproduce
1. click on the key symbol
2. enter credentials
3. click on save 

### Expected behaviour
should save the credentials

### Actual behaviour
nothing - the color of the button turns from green to blue 

### Configuration
**Operating system**:   
ubuntu 16.04
   
**Browser**:   
   chromium
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    
       1.0.2
       
**Nextcloud version**:
   11.0.2
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brantje** [comment]
This is solved in 1.1 version of the extension.
