### ISSUE TITLE
Passman Extension for Firefox not decrypting the passwords.

### ISSUE THREAD

**Issue by Arnauec** [nextcloud/passman-webextension#277]
### Steps to reproduce
1.  Add account of Nextcloud in Firefox version 62.0 (64-bit), using MacOs from the last version.
2. Add vault password to decrypt the passwords.
3. The passwords are not decrypted.

### Expected behaviour
The passwords should be decrypted properly.

### Actual behaviour
It seems like it can not decrypt the passwords correctly.
<img width="459" alt="screen shot 2018-09-15 at 12 50 55" src="https://user-images.githubusercontent.com/22740717/45585524-0aeb9400-b8e6-11e8-8530-93e556545b06.png">

### Configuration
**Operating system**: 
MacOs 10.13.6
**Browser**: 
Firefox version 62.0 (64-bit)
**Extensions that might cause interference**: 
I have tried to disable all of them.
**Passman version**: 
2.1.4
**Extension version**: 
2.1.1
**Nextcloud version**: 
Nextcloud 13.0.6

**Comment by budachst** [comment]
What makes you think, that the extension does nor decrypt the passwords it fetches from Passman? If the vault password would be wrong, you wouldn't be able to connect to the vault in the first place.

Or maybe, I misunderstood your issue. If so, please elaborate.

**Comment by Arnauec** [comment]
I have retried everything today and I realised the fault was on me. Thing is I thought that when it said password's vault, I could leave it empty and that it was an optional option. It is working fine now, sorry for the trouble.
