### ISSUE TITLE
how to add custom field

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/passman-webextension#28]
### Steps to reproduce
1.open web site with more than user/password fields
2.all fields have the passman-key
3.click on a key

### Expected behaviour
all key fields should be shown including the current content.

### Actual behaviour
only user id and password are shown
as a user I hardly can find out the internal name of the custom field.

### Configuration
**Operating system**:   
ubuntu 16.04
   
**Browser**:   
   chromium
   
**Extensions that might cause interference**:   
   
   
**Passman version**:    
       
       
**Nextcloud version**:
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brantje** [comment]
Adding custom fields can be done with the nextcloud app.
Editing credentials is for now not supported

**Comment by ferdiga** [comment]
welI I sought about the initial saving.
If not supported it would be helpful to say so in the app.
"Please add custom fields in the nextcloud app" + link to the documentation how to do this.

**Comment by brantje** [comment]
We have very little screen space in the password picker and the browser action.
We don't have the space to make a full featured editor in the page, hence the username / password fields.
The credential will be saved with the current page title as label.
