### ISSUE TITLE
distinguish between subdomains

### ISSUE THREAD

**Issue by LimitlessGreen** [nextcloud/passman-webextension#281]
It would be nice if passman could distinguish between subdomains.

For example **siteone.domain.com** is an other website than **sitetwo.domain.com**.
But passman shows the same passwords for both sites.

**Comment by wjwieland** [comment]
Can verify that the URL identification is lacking.  It is not just that either: If I have two separate URL's - for example -
mymachine.mydomain.com/url1
and 
mymachine.mydomain.com/url2

I end up having to select between the two every time.  Not handy.....

**Comment by IBBoard** [comment]
For reference of anyone who finds this later, if the subdomains differ then Passman should be able to handle this. Just make sure that "Ignore subdomain for site matching" is disabled under "Advanced Settings".

(Note: This will also mean that a password created for "login.example.com" *won't* be returned if they also put a login form on the main www.example.com - you can't have it both ways. It's not common, but I have seen it occasionally - e.g. Namecheap use ap.www.namecheap.com for some pages)
