### ISSUE TITLE
no export

### ISSUE THREAD

**Issue by lmjst** [nextcloud/passman-webextension#286]
### Steps to reproduce
1. export
2. settings
3. settings
4. export
5. password
6 Starting export
7 Decrypting credentials
8 nothing happern

### Expected behaviour
export csv

### Actual behaviour
nothing

### Configuration
ubuntu

**Browser**: 
firefox and chromium
**Extensions that might cause interference**: 

**Passman version**: 
Version: 2.1.4
**Extension version**: 
2.1.1

**Nextcloud version**: 
   Nextcloud 12.0.4
#### Browser log

</details>   
thanks

**Comment by Oliv4945** [comment]
@lmjst no export available from the extension, please open an issue [here](https://github.com/nextcloud/passman), but before update Passman, lot of issues have been solved lately.
The last one is you have to use Chrome, it does not work in Firefox for now

**Comment by animalillo** [comment]
Please check if it works with passman server 2.3.1

Also note, this is not a webextension issue, it's a passman core issue. The bugs on the web interface go to: https://github.com/nextcloud/passman
