### ISSUE TITLE
[Regresssion] Credentials are not stored automatically

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#30]
### Steps to reproduce
1. Enter into a site where you have already a user but passman doesn't know yet the credentials
2. Enter the credentials you know

### Expected behaviour
Credentials should be saved automatically, or ask for save them

### Actual behaviour
No credentials are saved

### Configuration
**OS**: Arch linux   
**Browser**:   Firefox 52.0.2
**Passman version**:    
**Extension version**:  1.1.2        
**Nextcloud version**:

**Comment by brantje** [comment]
Did the yellow bar appear?

**Comment by adocampo** [comment]
What yellow bar? (so, no, it does not appear...)

**Comment by brantje** [comment]
Might be caused by [this](https://github.com/nextcloud/passman-webextension/blob/master/js/background/inject/inject.js#L170) line.

**Comment by adocampo** [comment]
If  can do something to test it, please tell me.

**Comment by brantje** [comment]
Would be nice. Currently at work, so can't do other stuff than my work.
If you remove the following lines:
```
 if(getLoginFields()){
            API.runtime.sendMessage(API.runtime.id, {method: "clearMined"});
            return;
}
```
js/background/inject/inject.js line 170

Does the yellow bar appear again?

**Comment by adocampo** [comment]
Sorry, I do not find inject.js under my .mozilla directory...

**Comment by adocampo** [comment]
Removing that code seems to work.

**Comment by adocampo** [comment]
@brantje I've edited the inject.js file loaded the passman extension as a temporarily addon

**Comment by brantje** [comment]
Thanks for testing, just arrived home =)
