### ISSUE TITLE
Passman is disabled by Firefox because it can't be verified

### ISSUE THREAD

**Issue by bestouff** [nextcloud/passman-webextension#304]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system**: 

**Browser**: 

**Extensions that might cause interference**: 

**Passman version**: 

**Extension version**: 

**Nextcloud version**: 
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Mte90** [comment]
I can use it without any issue

**Comment by bestouff** [comment]
Which version of Firefox ?

**Comment by Mte90** [comment]
I am using the nightly version.
There was an issue with firefox months ago about certificate expiration for addons but this was fixed with an update.

**Comment by bestouff** [comment]
Ok yes, there was a problem with FF 60, and it seems fixed in FF 68.  
The only trouble is that 60.0 is what is used in Debian stable.

**Comment by Mte90** [comment]
There aren't any updates? because I think that the lts got an update

**Comment by bestouff** [comment]
Not as of 5mn ago.

**Comment by bestouff** [comment]
FF-ESR is at `60.8.0esr-1~deb10u1` on stable (and `68.0.2esr-1` on testing)

**Comment by Mte90** [comment]
The issue happened in may and that release is of july, https://hacks.mozilla.org/2019/05/technical-details-on-the-recent-firefox-add-on-outage/
It is something that doesn't involve this project but Firefox and debian on stable. I am on sid using nightly on debian so I didn't saw this problem.

**Comment by bestouff** [comment]
Ok, I get it.
