### ISSUE TITLE
if user is an email -> no user set -> extension doesn't detect the credentials

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman-webextension#32]
### Steps to reproduce
1. set up passman
2. add a credential for a site like flattr.com where the username is an email and just save the email
3. acces the page and try to find the login for the page

### Expected behaviour
passman should detect that email is used for login/username -> passman would detect the credential

### Actual behaviour
passman doesn't find an credential -> but with the search I can find the saved one -> I click on it and passman asks to update the url -> even after updating the url passman can't find the credential

### Configuration
**Operating system**:   Win 10

   
**Browser**:   Firefox 52
   
   
**Extensions that might cause interference**:   none
   
   
**Passman version**:   2.1.1 

**Extension version**:    1.1.3
       
       
**Nextcloud version**:   11.0.2

**Comment by brantje** [comment]
What field did you filled in, the username field or the email field?

**Comment by jones4410** [comment]
I just filled in the email field... but in this and some other cases the email is username as well... so I think it would save some headache if passman could use email as username if there is no username set...

**Comment by brantje** [comment]
[should](https://github.com/nextcloud/passman-webextension/blob/master/js/background/inject/inject.js#L12) work already...

**Comment by jones4410** [comment]
in version 1.1.3?
strange... doesn't work for me... at least with flattr... but I think it's general because if I search the entry, passman doesn't show a username... and I think the credential is not shown because the username is "missing"...
