### ISSUE TITLE
no error if extension can't connect to server

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman-webextension#35]
### Steps to reproduce
1. Setup nextcloud with passman
2. Setup passman extension
3. shut down nextcloud server
4. try to sync extension with server

### Expected behaviour
The Passman-extension should show an error message: "couldn't reach nextcloud/owncloud server with passman" or something similar

### Actual behaviour
Extension can't sync but doesn't tells anything

### Configuration
**Browser**:   Firefox 52
   
   
**Passman version**:   2.1.1 

**Extension version**:    1.1.4
       
       
**Nextcloud version**:   11.0.2

**Comment by brantje** [comment]
An icon can't describe the reason why it can't connect. I can indicate that the extension is locked.
Maybe an error every 5 min orso?

**Comment by jones4410** [comment]
maybe... Or the popup once and then some kind of notification in the Passman extension itself... And then my Idea was that a changed icon (like if its locked) would indicate, that there is something to read inside the extension...?
Sorry for my english...
