### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-webextension#36]
Make use of the [i18n](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n) API to make the extension translatable. More info [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization).

**Comment by adocampo** [comment]
Will you help in translating into Spanish or Catalan? I'm native speaker of both and I can contribute with them.

**Comment by brantje** [comment]
Yes, i speak Dutch native, @animalillo speaks Spanish / Catalan i think :P.
Maybe ask nextcloud to setup a transifex for the extension, after i figured it out.

**Comment by animalillo** [comment]
i do not have transiflex access tho xD

**Comment by adocampo** [comment]
Well, with transifex @animalillo and I can translate the extension into es_ES/ca_ES as quick as lightning!

**Comment by brantje** [comment]
![image](https://cloud.githubusercontent.com/assets/2758767/25397428/89cbad16-29e8-11e7-9109-d8cb979d6306.png)
Started to implement i18n

**Comment by brantje** [comment]
[Adding translations](https://github.com/nextcloud/passman-webextension/wiki/Adding-translations)

**Comment by jones4410** [comment]
Just added German translation in Transifex ;)
Thanks for your work on Passman.
