### ISSUE TITLE
Need to cancel Mozilla default password-remember screen

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman-webextension#37]
Is it possible for Mozilla to replace the default password screen? 
I mean, do not need the default remember-password section of the mozilla when using Passman

![2015-06-02-16-51-47-8fe4c1](https://cloud.githubusercontent.com/assets/297968/25166759/8cd43404-24e5-11e7-951e-78bfc20210ea.png)

Is there a way to turn off Mozilla's own feature?

_### Do not consider the red circle :)._

**Comment by brantje** [comment]
I've been looking to turn it off (by hiding the password field on submit), however in some cases this breaks websites. 
Not sure if an webextension has access to that popup, that's why i made that yellow doorhanger, i know that could be better.

So if anyone know how i can make use of the "save password popup" (for both FF and chrome), please link me, i can implement it without problems.

**Comment by emresaracoglu** [comment]
Address bar: `about:preferences#security`, -> `Remember password for sites` -> uncheck
I tested now and work

![fireshot screen capture 001 - first-look-at-the-new-tab-based-preferences-in-mozi_ - i1-news_softpedia-static_com_images_news2_first-look-at-the-ne](https://cloud.githubusercontent.com/assets/297968/25168855/ba6712f8-24ed-11e7-996f-d0be3a519553.png)

I do not know what the value in the config file* is for this but I will research like you (_*about:config_)

**Comment by brantje** [comment]
Hmm yea, that turns it off completely. For sure a solution, but not neat imo.
Need to test when chrome / firefox shows the 'Save password' popup. 
Maybe test with different css styles.
`display: none` -> This will stop firefox / chrome from grabbing the password, but it also has a possibility to break sites.
`visibility: none` -> untested

**Comment by emresaracoglu** [comment]
I will create a subject for it in Mozilla's own forum site and I will send an email to the Lastpass development team.. Maybe I hope they can help :)

**Comment by brantje** [comment]
I don't think they will help the serious competitor :P.
Do you know if lastpass extension is able to hide the "Save password popup" ?

**Comment by emresaracoglu** [comment]
Yes, I was using Last Pass for few years and it never seemed

**Comment by yfdyh000** [comment]
> I do not know what the value in the config file* is for this but I will research like you (*about:config)

`signon.rememberSignons` through DOM inspector.

**Comment by emresaracoglu** [comment]
@yfdyh000 tested, right on time! 
This can solve the problem in FF.

**Comment by brantje** [comment]
Would there be a way for chrome?

**Comment by brantje** [comment]
Closing, seems impossible for webextensions to alter browser settings.
Sources:
- http://stackoverflow.com/questions/37241450/how-to-change-firefox-preferences-aboutconfig-using-the-new-webextensions-api

And mozilla irc:
```
<brantje> Hi all, i wrote an webextension that manages passwords.
<brantje> Is it possible for an extension to turn off firefox password manager?
<not-freaktechnik> brantje: no
```
