### ISSUE TITLE
Save password bar DIV bug for some sites

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman-webextension#38]
![passman1](https://cloud.githubusercontent.com/assets/297968/25169575/368685ec-24f0-11e7-9350-10a2959b782c.png)

### Steps to reproduce
1. Enter a mail service ### (z o h o)
2. Access mail panel
   
**Browser**:   
   Mozilla FF 52.0.2
   
**Passman version**:   
1.1.5

**Comment by brantje** [comment]
You've got an url i can test?

**Comment by emresaracoglu** [comment]
Absolutely, [URL](https://home.zoho.com/home)

**Comment by brantje** [comment]
#41 will solve this.

**Comment by brantje** [comment]
@emresaracoglu Ok if i close this one?

**Comment by emresaracoglu** [comment]
@brantje 🆗
