### ISSUE TITLE
Edit / Remove buttons in extension

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman-webextension#39]
Is it possible for future versions of the plan to quickly create `Edit `and `Remove `buttons for login-datas?
do not need to direct these buttons directly to the site, this datas can be updated **in** the Passman plugin.

![passman2](https://cloud.githubusercontent.com/assets/297968/25170242/8237a23a-24f2-11e7-9fd5-f13c14886ac4.png)

**Comment by brantje** [comment]
The space you indicated is used for the OTP.
![afbeelding](https://cloud.githubusercontent.com/assets/2758767/25170763/f0dace1c-24eb-11e7-8415-92cc24fd8aeb.png)
I've been thinking to add edit / remove buttons. 
Problem is we've got only a little screen space, and if i want a edit screen then it must has the same functionality as in Passman self.

**Comment by emresaracoglu** [comment]
![passman6 fw](https://cloud.githubusercontent.com/assets/297968/25180500/e704561c-2516-11e7-8ac0-a8af3ef114f3.png)

**Comment by brantje** [comment]
![image](https://cloud.githubusercontent.com/assets/2758767/25619540/8dab4ac8-2f4b-11e7-8a8c-70eaf503ee62.png)
![image](https://cloud.githubusercontent.com/assets/2758767/25619546/94e66e08-2f4b-11e7-955a-9c4246a8c161.png)

**Comment by emresaracoglu** [comment]
This is a great look!

**Comment by emresaracoglu** [comment]
@brantje When will you release the new version?

**Comment by brantje** [comment]
Not sure yet, thinking about redesigning the password picker too.

**Comment by brantje** [comment]
Closing, new version `1.2.5` solves this.

**Comment by emresaracoglu** [comment]
👍
