### ISSUE TITLE
Password picker font

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman-webextension#40]
I think there is a serious problem with the visibility of the writings and maybe this is no problem for small screens but creating problem for wide displays

I think a clearer font and size can be readjusted
   
![passman3](https://cloud.githubusercontent.com/assets/297968/25170647/fe55636a-24f3-11e7-946a-729ead9e2d2c.png)

**Browser**:   
Mozilla FF 52.0.2
   
**Extension version**:    
1.1.5

**Comment by brantje** [comment]
@elioqoshi What font and font-size do you suggest?

**Comment by emresaracoglu** [comment]
`font-family: Tahoma, sans-serif;`

```
#password_picker .tab-content {
	font-size: 14px;
}
.account {
	padding: 4px 6px 4px 9px;
}
.account > small {
    color: #6d6d6d;
    font-size: 11px;
}
```
![passman4](https://cloud.githubusercontent.com/assets/297968/25171789/a5871db0-24f7-11e7-99fb-f959038f9e04.png)

What are you thinking?

**Comment by brantje** [comment]
How does `font-family: 'Open Sans', Frutiger, Calibri, 'Myriad Pro', Myriad, sans-serif;` look?
Open Sans is the default font for Nextcloud.

**Comment by emresaracoglu** [comment]
That's very nice! You thought good the default font type of Nextcloud
Looks so good with `font-size: 15px`

**Comment by brantje** [comment]
Can you make a PR? Currently at work so can't do much.

**Comment by elioqoshi** [comment]
Perfect, thanks!
