### ISSUE TITLE
[Feature Request] Generate strong password on new registrations

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#43]
### Steps to reproduce
1. Enter a wordpress registration site (for example: http://bixi.io/wp-login.php?action=register)
2. Select the username

### Expected behaviour
If the site does not exists, passman should let create a strong password and store it.

### Actual behaviour
Nothing, like if passman where not even installed

### Configuration
**Operating system**:   
Arch linux
   
**Browser**:   
   Firefox

**Passman version**:    
2.1.1

**Extension version**:    
1.1.5       
       
**Nextcloud version**:
   11.0.2

I do not know if it's supossed to work, I had in my memory as it worked before... perhaps I dreamt it or perhaps is a regression. Yo can try it on the URL I gave up here.

**Comment by brantje** [comment]
This already exists.
![afbeelding](https://cloud.githubusercontent.com/assets/2758767/25230339/dbf8b5e8-25d3-11e7-9fa4-dc5f0f9f9a49.png)
The login field is not detected because it doesn't contain password fields.
Therefore the extension skips this form. (Also firefox does the same).

**Comment by brantje** [comment]
Example of how it works correctly: http://bootsnipp-env.elasticbeanstalk.com/iframe/2X0r#

**Comment by adocampo** [comment]
I can't see the passman icons... :|

(http://i.imgur.com/u2OqIip.png)

**Comment by brantje** [comment]
That's is because the form is not detected by the extension because that form is missing a password field.

**Comment by emresaracoglu** [comment]
The same is true for this site: [SoundCloud](https://soundcloud.com)
Can something be done for this situation?

**Comment by brantje** [comment]
Nope not much, we use the same code firefox uses for detecting login forms.

**Comment by brantje** [comment]
SoundCloud is different btw. They don't even have an form :/

**Comment by emresaracoglu** [comment]
![passman8](https://cloud.githubusercontent.com/assets/297968/25232854/78e9cf98-25e5-11e7-8adc-6e6c8e49c82f.png)

I re-installed LastPass for screenshots.. Even if there is no icon, I can access it from the menu with right click
_Also, I can't believe this label: "Not a passman problem". Do you need such a label?_ @animalillo

**Comment by adocampo** [comment]
"Problem" acknowledged: You can't generate a password if no form is shown on the website. Obvious.

As suggestion, there are plenty strong password generators addons, perhaps you can add that functionality to passman in the future in order to use less addons.

**Comment by brantje** [comment]
`perhaps you can add that functionality to passman in the future in order to use less addons.`
As i said, passman has it's own password generator. It will show up when it detects a password field.

**Comment by adocampo** [comment]
>  As i said, passman has it's own password generator. It will show up when it detects a password field.

Yes, yes, yes... I expressed myself pretty bad. What I suggested was to add a contextual menu entry (or another button in the widget) , independtly if there are a password field or a login form, to generate a random strong password (perhaps predefined on passman server settings or in the browser passman extension).

You can use those random generated passwords for other purposes, like give them to other users for temporary passwords you'll never store, etc. Other passwords managers have that function and with passman we must have another extension, like this: https://addons.mozilla.org/es/firefox/addon/passgen, to achieve that extra funtionality.

**Comment by brantje** [comment]
Ahhh that makes it more clear. Thanks for clarifying.
It's possible to detect right clicks on input fields (not specific password fields), and fill that one with a random generated password.
Maybe an idea to copy the generated password to clipboard?

**Comment by adocampo** [comment]
Yes, I think the best way should be a right click menu (passman --> copy random password to clipboard) (or even a new button on the passman widget icon) and copy that random password on the clipboard better than the need to find a textbox field and put a password there to cut/copy it afterwards.

**Comment by brantje** [comment]
![image](https://cloud.githubusercontent.com/assets/2758767/25245690/9f08051c-2605-11e7-8a5b-a39daf7653fc.png)

**Comment by adocampo** [comment]
OSOM!!! That's what I asked for! :D

**Comment by brantje** [comment]
Fixed in the `1.1.8` release. XPI is available for download, chrome users will receive the update soon.
