### ISSUE TITLE
Disappearing in Modal

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman-webextension#44]
![passman7](https://cloud.githubusercontent.com/assets/297968/25233423/6eaa1950-25e7-11e7-8e75-9dcc951b4464.png)

**Site**: 
https://www1.dsmart.com.tr/?login=true&ReturnURL=/online-islemler

**Browser**:   
Mozilla FF 52.02
   
**Extension version**:    
1.1.5

**Comment by brantje** [comment]
Hmm `z-index: 999` is not enough in this case.
`z-index: 9999;` solves it.
