### ISSUE TITLE
iFrame Windows

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman-webextension#46]
![passman9](https://cloud.githubusercontent.com/assets/297968/25242630/fcee4220-2602-11e7-9be7-d9f79d9c549c.png)

**Comment by brantje** [comment]
Fixed with using iFrames. Fixed in d1e28cc06314b7829d2aabc8e22dafb0865167a3

**Comment by emresaracoglu** [comment]
That's good!
