### ISSUE TITLE
Move credential suggestions

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#49]
### Steps to reproduce
1. Click on the username field on a website where you have entered with several users, or which login field has the same name of other sites and firefox remembers several usernames.

### Expected behaviour
We should see both firefox and passman login selector

### Actual behaviour
We see firefox logon selector above passman's one. Making it annoying to select the wanted login.

### Configuration
**Operating system**:   
Arch linux
   
**Browser**:   
Firefox 52
   
**Extensions that might cause interference**:   
 None  
   
**Passman version**:    
1.1.5

**Extension version**:    
       
       
**Nextcloud version**:
  11.0.3 

As an Image worth a thousand words, see what I mean.

[http://i.imgur.com/Zsp5uWf.png](url)

I think perhaps passman selector should be selectable on the passman widged
http://i.imgur.com/mXMIZon.png
So firefox selector won't interfere with passman's one.

What do you think?

**Comment by brantje** [comment]
Can you check if Firefox password manager is disabled, it still happens? See the other issue how to disable.

**Comment by brantje** [comment]
Issue #37

**Comment by adocampo** [comment]
Sorry for the delay.
Yes, it still happens, because I'm not speaking about the password manager, but the... how to say, textbox memorized entries... 
![Like this](http://i.imgur.com/Zsp5uWf.png)

**Comment by brantje** [comment]
Ah yea, that is the auto complete box. I could bypass it by adding a autofill=false, but that will disable autofilling for the whole form.

**Comment by adocampo** [comment]
That's why I suggested to make clikable the items on the list placed on the widget 
[](http://i.imgur.com/mXMIZon.png)

**Comment by brantje** [comment]
Problem is i can't bind events to the auto complete box. Since this build in to the browser.

**Comment by adocampo** [comment]
It seems LastPass disables firefox autocomplete box. Not a bad idea.
![](https://addons.cdn.mozilla.net/user-media/previews/full/171/171887.png)

**Comment by brantje** [comment]
Uch, it annoys me that the password pickers looks like the lastpass one >_>.
Maybe i'll redo the picker with material design. 

As for this issue, at the moment it has 2 feature requests:
- Fill username / password when credential is clicked in the browser action
- Disable autofill

Do i create new issues for those features, or do you want to?

**Comment by adocampo** [comment]
Yes I got surprised how laspass password picker looked like passman's one, I thought you were inspired by lastpass xD

Perhaps will be better if you create the issues, I'm not very familiar yet with github.

**Comment by jones4410** [comment]
the option "disable browser autofill" doesn't disable firefox's textbox dropdown as @adocampo showed in screenshot

**Comment by brantje** [comment]
Hmm strange. Don't know a way for a webextension to turn off the password management in browsers.
Therefore i've [added](https://github.com/nextcloud/passman-webextension/wiki/Disabling-your-browser-password-manager) a page to the wiki explaining how to disable them.

**Comment by jones4410** [comment]
Ah, thanks for this...
But I thought of this dropdown:
![grafik](https://cloud.githubusercontent.com/assets/22591354/26032343/6484a10e-3891-11e7-899f-6f7e63299afc.png)
which is annoyingly popping up in front of passmans password picker. Any way to turn this off?

**Comment by brantje** [comment]
Yes see: https://github.com/nextcloud/passman-webextension/wiki/Disabling-your-browser-password-manager

**Comment by jones4410** [comment]
sorry... yes I had already turned this of, but Firefox still presented me the dialog (see screenshot).
[This Mozilla support entry](https://support.mozilla.org/en-US/kb/control-whether-firefox-automatically-fills-forms?redirectlocale=en-US&redirectslug=control-firefox-automatically-fills-in-forms#w_prevent-firefox-from-storing-form-entries) fixed it for me, but turns it off for all forms.
If there is a way, I would like to see passman turning it off for password forms.

**Comment by brantje** [comment]
The problem is, 'old' extensions had access to change the settings.
Passman uses the new webextension technology, which doesn't has access to such settings (yet?).
This is the same in Chrome and Opera, i'm looking for a way to hide it with the extension, but so far didn't found anything.

**Comment by brantje** [comment]
Also we have #37 for this

**Comment by brantje** [comment]
Disabling it with an extension is impossible, see #37 for an explanation.
