### ISSUE TITLE
Firefox performance issues

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman-webextension#53]
### Steps to reproduce
1. Open a website you have credential(s) stored for
2. Click "edit" credential

### Expected behaviour
the edit screen should show up

### Actual behaviour
Firefox freezes -> Error
![grafik](https://cloud.githubusercontent.com/assets/22591354/25779561/e49e9cf8-331b-11e7-8ca5-dda49ac21282.png)
If I click on continue running script, Firefox crashes completely

### Configuration
**Operating system**:   Win 10
**Browser**:   Firefox 53
**Passman version**:    2.1.2
**Extension version**:    1.2.5
**Nextcloud version**:  11.0.3

**Comment by brantje** [comment]
Thanks for reporting. This one is gonna be hard to debug, it crashed Firefox twice already.

**Comment by jones4410** [comment]
and firefox even crashes if I klick on "debug script"

**Comment by brantje** [comment]
Jup have the same here. Already narrowed it down to the function that causes it.

**Comment by adocampo** [comment]
Oops, I also noticed it on another opened issue, besides the slow performance.

**Comment by adocampo** [comment]
Oh, I loved the Material Design theming... but it's pretty heavy on high end computers and considerably slow on low powered ones :(

**Comment by brantje** [comment]
Please try 1.2.6. It's far from pretty, but functional for now. Will work on the redesign this week.

**Comment by adocampo** [comment]
Noticeably faster, specially on the Atom processor machine, on the i7 draws itself immediatly.
