### ISSUE TITLE
Overall performance 1.2.5

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#54]
Version 1.2.5 seems pretty heavy, or at least, it seems slow at drwaing itself. I tried first on a Quad Core Cherry Trail Z8350 4GB RAM, and it took several seconds since I've clicked on the icon unitl it drawed the GUI. After that, I tried it on a i7 with 8GB RAM and it was a lot faster, but you can notice how hard to draw it is.

Furthermore, clicking on "Edit" button on a password entry on the list, hangs completely firefox until the "unresponsive script" popup appears.

**Comment by brantje** [comment]
We have #53 for the locking up issue. Seems that the new UI is pretty heavy indeed...

**Comment by brantje** [comment]
Closing, redesign will be reverted soon. But we will not cut on features ;).
