### ISSUE TITLE
clicking on "select vault" results in small window but no chance to select anything

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman-webextension#55]
### Steps to reproduce
1. go to settings
2. click on "select vault"

### Expected behaviour
dropdown with the vaults to choose from should appear

### Actual behaviour
passman gets small
![img_20170507_121045](https://cloud.githubusercontent.com/assets/22591354/25779799/d7830254-331e-11e7-948e-0970a8d77c78.jpg)
resulting in something like this, but no chance to change anything

### Configuration
**Operating system**:   Win 10   
**Browser**:   Firefox 53
**Passman version**:    2.1.2
**Extension version**:    1.2.5       
**Nextcloud version**:  11.0.3

**Comment by brantje** [comment]
Yea the redesign is having some serious performance issues on firefox and thus will be reverted soon.
