### ISSUE TITLE
Non working edit entry

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#56]
### Steps to reproduce
1. Click on the edit entry arrow
2. Modify some field or add a new one
3. Click save

### Expected behaviour
It should modify the passman entry on NC/OC and sync amongst clients.

### Actual behaviour
Does nothing.

### Configuration
**Operating system**:  Arch Linux / Windows
**Browser**:   Firefox 53
**Passman version**:    2.1.2
**Extension version**:    1.2.6
**Nextcloud version**: 11.0.3

**Comment by brantje** [comment]
Fixed in 1.2.7
