### ISSUE TITLE
How to connect Chromium extension ?

### ISSUE THREAD

**Issue by vincegre** [nextcloud/passman-webextension#58]
Just installed the extension in my NextCloud and have setup a locker with a good password. I have then installed the extension in Chromium (version 60 on Linux Ubuntu 16.04.2) but when I right click on Extension in the adress bar, there is no Options avalaible, and a left click just popups a big blue square box and nothing else happens :(
Am I missing something obvious ?

Thanks

Vincèn

**Comment by brantje** [comment]
Please use the issue template. We're missing critical details here. Feel free to create a new issue that follows the template.

**Comment by brantje** [comment]
Little addition: When you click the browser icon, a small setup screen should appear. Guiding you how to setup the extension

**Comment by vincegre** [comment]
Oki will repost it with all details but for info when I right click the browser icon the "Options" choice is always greyed out ! Restarted Chromium but not better :(
Please close this one, I reopen a new one complete ;)
