### ISSUE TITLE
How to connect extension in Chromium ?

### ISSUE THREAD

**Issue by vincegre** [nextcloud/passman-webextension#59]
### Steps to reproduce
1. Downloaded the extension from the Chrome Store and it installed by itself in Chromium
2. Options button on icon of extension in browser is always greyed out :(
3. Regular click on extension icon displays only a large blue square !

### Expected behaviour
Tell us what should happen

Should be able to access the Options choice to setup extension

### Actual behaviour
Tell us what happens instead

Option button stays greyed out !

### Configuration
**Operating system**:   

Ubuntu 16.04.2 LTS 64 bits
   
**Browser**:   

Chromium 60.0
   
**Extensions that might cause interference**:   
   
Lastpass
   
**Passman version**:    

2.1.2

**Extension version**:    
       
1.2.7
       
**Nextcloud version**:
   
11.0.3

Not sure what to include for logs, please let me know if needed and what ?

Thanks

**Comment by brantje** [comment]
Thank you for reporting this issue. I've reinstalled the extension and got the same result. Narrow it down to a typo in the js include files. Need to get access to the server to push an update. Fill be fixed today.

**Comment by vincegre** [comment]
cool, was afraid I had missed something basic :D Will need to reinstall/upgrade extension from Chrome store then once update done right ?

**Comment by brantje** [comment]
Chrome will update extensions automatically, but it's possible to force the update.

**Comment by vincegre** [comment]
oki, I'll wait for update of this issue as I guess you'll close it as soon as you have corrected the bug ;)

**Comment by brantje** [comment]
In fact, i already fixed the bug, but need to push an update. But left my mobile phone at home so can't 2FA atm.

**Comment by vincegre** [comment]
Héhé no problem, just impatient to test that ;)

**Comment by brantje** [comment]
@vincegre Should be fixed now =). `V1.2.8` is live.

**Comment by vincegre** [comment]
Thanks a lot, works fine now ;) You are the best :+1:
