### ISSUE TITLE
Same option twice in 2 languages ?

### ISSUE THREAD

**Issue by Draky50110** [nextcloud/passman-webextension#62]
Hi.

I'm using Firefox extension 1.2.8 and I think there is a double entry with same result in options.

![passman-webext](https://cloud.githubusercontent.com/assets/1558487/25947747/00d3b434-3651-11e7-9dff-431a55de97f5.png)

Same in french and english... not sure what it does if both are not the same settings (check one and not other lol)...

**Comment by brantje** [comment]
Nope, option disables auto filling for the extension (filling in username & password when found).
The other one should disable the autofill function of the browser.

**Comment by Draky50110** [comment]
Ok, thanks for tips :)
