### ISSUE TITLE
Ignore subdomain function

### ISSUE THREAD

**Issue by florianaudon** [nextcloud/passman-webextension#63]
### Expected behaviour
I think with the option "Ignore subdomain", passman must return the same result if I'm on login.example.com and on login2.example.com

### Actual behaviour
 It's doesn't ignore subdomain. For example if I go to login.example.com and login2.example.com it's not the same for passman

### Configuration
**Operating system**:   
Archlinux
   
**Browser**:   
 Chromium 58
   
**Passman version**:    
1.2.8

 In my console, if I execute the following code
```
URLobj = new window.URL("https://login.example.com");
var host = URLobj.host
var splittedURL = host.split(".");
var result = host.match(/[^./]+\.[^./]+$/);
var TLDlength = 0;
if(result){
      TLDlength = result[0].length;
}

baseHost = splittedURL.slice(-TLDlength - 1).join(".");
```
baseHost will be egal to "login.example.com". Or baseHost is return if ignoreSubdomain is true.
Is it normal?
Maybe I've misunderstanding something.
Florian

**Comment by brantje** [comment]
Yea, that function is a bit buggy.
The original TLDlength code was this:
```
 {
    var TLDlength = url.getTLD(URLobj).split(".").length;
    baseHost = splittedURL.slice(- TLDlength - 1).join(".");
  }
```

If you like you can help me out with this, otherwise i'll look into it.

**Comment by florianaudon** [comment]
Ok, right now I haven't enough time. But I will look into it soon.

**Comment by brantje** [comment]
Thanks! =)

**Comment by florianaudon** [comment]
This functionality has been correct in pull request #67
