### ISSUE TITLE
Updating URL not working

### ISSUE THREAD

**Issue by Draky50110** [nextcloud/passman-webextension#69]
Hello.

Using 1.2.9 + FF 53, on a website, URL change is detected and the extension assks to update or not.
I click on update, yellow mention says "Saving..." but forever, and the new login URL is not edited.

**Comment by brantje** [comment]
Can you upgrade to 1.2.11 and try agin? https://releases.passman.cc

**Comment by brantje** [comment]
@Draky50110 any luck?

**Comment by Draky50110** [comment]
Never get it back with 1.2.11 so... nice :)
