### ISSUE TITLE
Non-working sites

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#71]
There are some websites whose login form must be different and passman is having a bad time trying to filling or even showing the blue shield icons on the credential filelds.

I had a list with several places, trying to gather several of them for you to realize what the problem could be. But now some of them are working, I do not know if is something fixed on latest versions of the plugin or perhaps some change on the server side.

The tiny list of non-working sites is:
 - netflix.com (passman shield icons shown, I can select my credentials, but login form complains as if the credentials were in blank, but selecting "show password" on netflix form, I can see the right password and email...)

![login](http://i.imgur.com/MOkKb9K.png)
![passman](http://i.imgur.com/E0SueLg.png)
![error](http://i.imgur.com/kUYtyrj.png)
![error](http://i.imgur.com/URk3944.png)
![error](http://i.imgur.com/B5HbZIc.png)

 - keepa.com (no shield icons shown on form, passman shows matching credentials)
![keepa](http://i.imgur.com/mGriIIu.png)
Now working sites are:
-  https://login.gearbest.com/
-  https://www.suse.com/

**Comment by brantje** [comment]
Login forms which are created with ajax / are inserted after load are currently not detected by the extension.
This is a known limitation / bug.

As for the sites that started working, i think it must be server side because i didn't change a thing to the detection.

Will look this weekend how to fix this.

**Comment by brantje** [comment]
Added fix for netflex. 
keepa.com is kinda 'special' 
Look at their dom structure:
![image](https://cloud.githubusercontent.com/assets/2758767/26720372/44b804d2-4788-11e7-98a9-2fc4f02de4bd.png)
Will think about a fix for it, but won't be high prio.
I've enabled support for ajax login forms. Performance wise, i don't notice much difference.

**Comment by adocampo** [comment]
Perfect! Once in home I'll test it on my atom's pc, to see if performance is noticeable.

**Comment by augustseptember** [comment]
Netflix.com is still not working for me. The credentials are right and synced via passman, but I have to retype the password to succeed... 

Seeing this when entering the site:
![netflixlogin](https://user-images.githubusercontent.com/6906270/33571786-6cb72ec8-d931-11e7-91b5-53b38cee6fd6.png)
And after clicking on login:
![netflixloginfailed](https://user-images.githubusercontent.com/6906270/33571859-9ae13942-d931-11e7-849d-21b5aeb75c93.png)
