### ISSUE TITLE
[Feature-request] Show some information when having problems connecting to server

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#73]
Today my letsencrypt certificate expired, I have NC inside a docker container and while I set up a letsencrypt container for renewing all my services, I have to renew the cert for nextcloud manually.

That made passman unable to connect to the server, but there was no information at all. Passman interface was like connected but with no passwords at all, and under settings, no vault appeared in the dropdown. Besides that, an annoying popup appeared every few seconds saying passman was unable to connect.

I think it would be useful to show some human readable information like "server unreachable", "SSL certificate out of date" or other useful information rather than the generic "error connecting to server" that can be anything.

Besides, and option to disable the annoying pop up would be also very appretiated. Lately I'm on a client's office and I must configure their proxy in order to reach the Internet and I have it configure on firefox but not in chromium, and the chromium's passman pop up appears every one and then, and its annoying. I need Chromium's proxy unconfigured, so now I have it closed until I need it and then close it again or suffer the pop up.

**Comment by brantje** [comment]
Sorry to get this late back to this. 
I've investigated this, unfortunately, i only get an generic error from chrome.

When the passman extension is locked, it won't refresh the credentials.
So when the notification is annoying, just lock the extension and the notification will go away.
I've implemented this behavior because i've experienced it myself. And because: Why refresh credentials if extension is locked? Makes no sense to me.

**Comment by Mte90** [comment]
I often receive Error on server or something like that (I don't remember the right error).
Maybe in case of this error report also the http error so as owner of the server we can investigate

**Comment by brantje** [comment]
Afaik chrome gives an generic error, not sure about Firefox. 
For fetching data i use the [fetch](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) method provided by Firefox and Chrome.

Small code for fetch, change accordingly 
```
fetch('flowers.jpg').then(function(response) {
  if(response.ok) {
    return response.blob();
  }
  throw new Error('Network response was not ok.');
}).then(function(myBlob) { 
  console.log('OK');
}).catch(function(error) {
  console.log('There has been a problem with your fetch operation: ' + error.message);
});
```

**Comment by brantje** [comment]
![image](https://user-images.githubusercontent.com/2758767/27094342-133ad552-506a-11e7-9b01-ab4e32c05677.png)
Nope, not much difference when an extension can't connect to the service.
Will add the error i get to the notification, might give useful errors in some cases.

**Comment by Mte90** [comment]
I have the error many times at day and report only a NetworkError.
It is possible add a settings to avoid this kind of notifications?
