### ISSUE TITLE
Error on parseUrl with more then two tld parts

### ISSUE THREAD

**Issue by welbert** [nextcloud/passman-webextension#74]
### Steps to reproduce
1. Save many site with more then two domain, like '.com.br'
2. Open whatever site with suffix .com.br, like www.google.com.br
3. Extension show up all sites with .com.br

### Expected behaviour
Show pass only on google.com.br

### Actual behaviour
List on *Steps to reproduce*

### Configuration
**Operating system**:   Windows

   
**Browser**:   Firefox 53.0.3
   
   
**Extensions that might cause interference**:   Nothing
   
   
**Passman version**:    2.1.2

**Extension version**:    1.2.12
       
       
**Nextcloud version**: 11
   
### Notes
After some test and debug extension, i see the problem.

On `js/lib/parseUrl.js` this [code](https://github.com/nextcloud/passman-webextension/blob/ccba76f790c584b92feab36c245fe3eddf1fb761/js/lib/parseUrl.js#L53) `var result = host.match(/[^./]+\.[^./]+$/); // catch the two last parts, it's de hostname and the tld` is the problem

This bug doesn't occurs on Extension 1.2.8

**Comment by welbert** [comment]
On this case, is a bug or bad configuration (Turn off Ignore SubDomain) ? For now, i'm using with not ignoring subdomain

**Comment by brantje** [comment]
@florianaudon Seems like your regex isn't perfect. Mind taking a look at it?

**Comment by florianaudon** [comment]
Yes, I will look on it.

**Comment by brantje** [comment]
Note, we should match against known tld's: https://github.com/131/node-tld/blob/master/effective_tld_names.json
Might make the extension bigger, but a regex to match all existing TLD's is almost impossible to write.
