### ISSUE TITLE
Feature suggestion: fill via contextmenu instead of icons

### ISSUE THREAD

**Issue by jschreuder** [nextcloud/passman-webextension#8]
The icons placed in username/password fields can be a bit annoying in sites that have heavy styling. I switched them off when using LastPass and am quite used to using the context-menu by right-clicking in the field and choosing which auto-fill I'd like from the available options. Any chance of a similar option in this extension? Or at least an option to switch off the icons and use the icon in my browser's top bar instead?

**Comment by brantje** [comment]
Can you make an example how last LastPass implements the right click option?
I'm thinking to add a fill button in the extension, might be a good alternative.

**Comment by jschreuder** [comment]
It's in Dutch, but the active top LastPass submenu option says "Autofill" basicly and offers me all available accounts for this domain (in this case one, but in others many). Works similarly in Chrome/Chromium and Firefox, this is in Chromium. Fill button in the extension would work just as well probably.

![schermafdruk van 2017-02-13 11-40-29](https://cloud.githubusercontent.com/assets/69116/22880157/6ea14756-f1e1-11e6-9ac1-d6f89138034c.png)

**Comment by brantje** [comment]
Dutch is no problem for me :P. Thanks for the idea, i'll look into it.

**Comment by jschreuder** [comment]
Awesome!
