### ISSUE TITLE
Cannot create vault in GUI

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#80]
### Steps to reproduce
1. Use an account with no vaults created yet.
2. Setup add-on.
3. At the step where you have to select your vault/enter your password, you cannot continue.

### Expected behaviour
Show a message that the vault should be created via the Nextcloud app.

### Actual behaviour
Only an empty field in the "vaults" selection is shown. When choosing it and using a new password, you cannot continue.

### Configuration
**Operating system**: Linux

**Browser**:  Firefox 53.0.3

**Passman version**: 1.0.3 

**Operating system**: Linux

**cloud server:** Nextcloud

**cloud version:** 12

**Comment by brantje** [comment]
Use the web GUI from passman it self to create vaults. The extension is as the word it say's, an extension of passman to provide you with your passwords in the browser. Not an in browser app of passman.

**Comment by rugk** [comment]
Come on, in any case it is a bad UX. It shows me an empty list entry and then tells me the password is wrong?

Actually if you really believe one should use the web UI to create the vault then at least state this in the UI after logging in in the WebExtension if there are no vaults yet. Such as: "Thanks for logging in to passman. However, you have no vaults created yet. Please first go to the website/NextCloud/OwnCloud instance and create one."

Thus, please reopen this issue in order to at least add such a note.

**Comment by brantje** [comment]
Showing a message that there are no vaults and should be created via passman is a good idea!
Thing is, i want to keep the extension small, if i add vault creation, then i also have to add all libs that are used for generating the sharing keys, which will add a some MB's.
