### ISSUE TITLE
OS' keyring integration

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#81]
Actually that's a huge feature request and maybe not possible (yet), but it would be nice if the master password could also be saved in the OS' keyring (MacOS or most Linux desktop environments – GNOME, KDE, e.g.) instead of in plain-text in a text file. This way, it would be protected and tied to the user account('s password).

This of course requires that browsers support a general (abstract) keyring integration for WebExtensions, which works independently from the OS. If that is not the case yet, we should urge them to implement this. This is explicitly also an aim of this issue. I think this add-on is a perfect example on why such a WebExtension API would be very useful.

**Comment by brantje** [comment]
Impossible due browser restrictions. I doubt browser makers will implement this.

**Comment by animalillo** [comment]
If you want to create an app that does such thing go ahead! we will add links if it fits our security standards.

**Comment by rugk** [comment]
Ah yeah, it could of course integrated in https://github.com/nextcloud/passman/issues/308, but in a browser extension it would be nicer IMHO. Maybe we can reopen this issue in the future. :smile:
