### ISSUE TITLE
Annoying "new login detected"

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#83]
The yellow "new login detected" is really annoying. You cannot even click it away, so it always stays there, even if you reload the site. Please remove it or make it at least dismissible.

Firefox

**Comment by brantje** [comment]
That yellow bar is a feature to save passwords directly to passman. You can ignore the site or close the bar.

**Comment by rugk** [comment]
I cannot close the bar. There is no button…
And I have no idea how to ignore the site as there is no button either.

It's simply a yellow iFrame…

![grafik](https://user-images.githubusercontent.com/11966684/26989525-b6930a54-4d53-11e7-850b-da3fb3d961c3.png)

### Configuration
**Operating system**: Linux

**Browser**:  Firefox 53.0.3

**Passman version**: 1.0.3 

**Operating system**: Linux

**cloud server:** Nextcloud

**cloud version:** 12

**Comment by brantje** [comment]
What site is it? Some sites do have problems. But calling it annoying and asking to remove is a bit dramatic imho.

**Comment by brantje** [comment]
Also under settings you can ignore sites.

**Comment by rugk** [comment]
Well… when one cannot hide it, it is indeed annoying. Especially in such a yellow fashion.

The site is in the screenshot: https://threema-forum.de/

**Comment by brantje** [comment]
Under settings you can ignore sites, and tld's.

**Comment by rugk** [comment]
Yeah, but there is no close button. So please reopen this issue. It seems to be site-specific, but I don't know what is special about the MyBB forum I linked…

**Comment by brantje** [comment]
Openened #85 for this

**Comment by brantje** [comment]
@rugk In 1.3.3 this bug should be solved. Can you confirm it works correct now?

**Comment by rugk** [comment]
I can confirm it works now.
