### ISSUE TITLE
Does not honor defaults for password generation

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#87]
### Steps to reproduce
1. Set some defaults in the web UI.
2. Create a password in the WebExtension.

### Expected behaviour
Use the defaults.

### Actual behaviour
Just uses some random defaults, with way too short passwords.

**Comment by brantje** [comment]
The web extension passwords and web ui password generators are not linked. You can change the extension generation settings under password generation.

**Comment by rugk** [comment]
Where? There is no such setting in v1.3.3.

**Comment by brantje** [comment]
![image](https://user-images.githubusercontent.com/2758767/27204482-bc41b7b6-522b-11e7-9e9c-e2e3c981611f.png)

**Comment by rugk** [comment]
There is no such thing. The top bar you have there is a sidebar in my extension and there is no 🔄 symbol:

![grafik](https://user-images.githubusercontent.com/11966684/27204515-eec9a8c4-522b-11e7-8ccf-fbd62e270af5.png)

**Comment by rugk** [comment]
So what? Do you use a more up-to-date version or a dev version and this is a new feature?

**Comment by florianaudon** [comment]
To have the window with configuration of your passwords you need to click on the symbol near the login/password fields?
![image](https://user-images.githubusercontent.com/7670696/27205464-4289419a-5231-11e7-9381-179469c6627b.png)

With the v1.3.3 I have the option

**Comment by rugk** [comment]
Ahh, it is not in the main window, however…
