### ISSUE TITLE
Can hardly click on icon in input fields

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#89]
When trying to log in on https://bugzilla.redhat.com/ you get two small input fields. I can hardly click on the small icons in these fields to get the screen for putting the password in there.

Finally I managed to do it by clicking a bit right of the icon and it seems to work.

### Configuration
**Operating system**: Linux

**Browser**:  Firefox 53.0.3

**Passman version**: 1.0.3 

**Operating system**: Linux

**cloud server:** Nextcloud

**cloud version:** 12

**Comment by brantje** [comment]
Not much to do about this. The icon is sized according to the input field.
