### ISSUE TITLE
Updating password shows Base64 rubbish (or not-so-rubbish??)

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#91]
### Steps to reproduce
1. I updated my password
2. Maybe when it has not been updated yet or so, search for this entry and show it.

### Expected behaviour
Show some sane thing.

### Actual behaviour
In all fields (password not checked, but username, URL etc.) it showed me a Base64. For my own security I'm not pasting it here.

Decoded it was something like:
```
{"iv":"I[…]","v":1,"iter":1000,"ks":256,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"r[…]","ct":"q35[…]"}
```

And this looks fishy… (like something encrypted)

When trying tom reproduce this a few seconds later (maybe now it has been uploaded or so…) it was normal again.

### Configuration
**Operating system**: Linux

**Browser**:  Firefox 53.0.3

**Passman version**: 1.0.3 

**Operating system**: Linux

**cloud server:** Nextcloud

**cloud version:** 12

**Comment by brantje** [comment]
Should be fixed in next version.

**Comment by brantje** [comment]
1.4.1 is live.
