### ISSUE TITLE
Can't connect to Nextcloud server

### ISSUE THREAD

**Issue by koug44** [nextcloud/passman-webextension#93]
### Steps to reproduce
1. Installing webextension from Mozilla website
2. Fill in server adresse, login and application password
3. Click «Next»

### Expected behaviour
The extension should synchronize with my nextcloud

### Actual behaviour
Error 500 on webserver. Here is a line in the apache log:

24.203.207.137 - dalexandre [16/Jun/2017:15:13:51 +0200] "GET /owncloud//index.php/apps/passman/api/v2/vaults HTTP/1.1" 500 6442 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"

### Configuration:
Nextcloud 12.0.0 on Debian 8 with PHP 5.6
   
**Browser**:   
Firefox 54 on x64 Linux

**Passman version**:    
2.1.2

**Extension version**:    
1.3.3

**Comment by brantje** [comment]
Seems you have a double slash in the URL. Don't know it that is the cause for the trouble.

**Comment by koug44** [comment]
Oh… I missed that ! It works without so thanks @brantje 

I keep the issue open as there's a room for improvement for the extension
