### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#94]
### Steps to reproduce
Go to https://github.com/nextcloud/passman-webextension/releases.

### Expected behaviour
Tagged releases.

### Actual behaviour
No tags. (looks as if there were no releases yet)

i.e.
Please [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your [releases](https://help.github.com/articles/about-releases/), so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

org: https://github.com/nextcloud/passman-webextension/issues/90

**Comment by brantje** [comment]
Nope, releases are handled by chrome store / AMO.

**Comment by brantje** [comment]
Also distributing older versions of the addon is a bad idea.

**Comment by rugk** [comment]
Are you kidding?
1. This thing is open-source. Tagging the source code is useful for knowing to which version a commit belongs to or when something was/will be fixed, etc.
2. Of course all users download the releases from the add-on sites. You also do not have to add the xpi files to the tags. Git tags are only for developers/contributors…
3. If one really wants to download an older version one can just use the source code without tags… So with each commit you are "distributing older versions of the addon". If you think this is bad make a closed-source version. (This is a joke!)
