### ISSUE TITLE
multiple nextcloud servers support

### ISSUE THREAD

**Issue by pafcioooo** [nextcloud/passman-webextension#99]
It is a feature request.

In settings there would be servers settings profiles each profile for different nextcloud server (or the same server but different vault).

It would allow seamlessly use ones different nextcloud servers private, companies etc. with passman.

**Comment by brantje** [comment]
Good idea. But for this, the whole backend of the extension has to be redone, since it's completely build on 1 server support.

**Comment by brantje** [comment]
Closed in favour of #115
